### ISSUE TITLE
[Question] WP ACF Flexible Content Components with Gridsome

### ISSUE THREAD

**Issue by owenclivee** [gridsome/gridsome#1025]
#I am still fairly new to Gridsome so I don't know if this is even possible but would be great if someone could let me know either way, and if it is...roughly how it could be achieved. (Thank you for your time!)

So, I have WordPress set up with ACF and can seemly pull the data through fine.  The set up I have is basically a page builder; using ACF Flexible Content to create dynamic components on a page by page basis. My intent is to allow the user to add as many components as they want, and the idea is that these would translate into my Vue components in Gridsome. This is my traditional set up for building WordPress sites and I am attempting to translate that over to JAMStack with Gridsome.

The trouble I'm having is pulling in the field data of page specific components. At first I thought I could run a page-query in the Vue component itself, but I now realise only static-queries can be used at the component level. And unfortunately a static-query won't really work because the same ACF component fields could exit on multiple pages and I have no way of passing a page id to the query. So I now assume I have to query the ACF component fields at the page level where I can use a page-query.

However, as a page could technically have an unknown amount as well as different variations of ACF components I see this causing an issue too. For example, Page 1 could have just 2 ACF components...a banner and slider, but Page 2 could have 10. Does this mean in my page template I would need to query all the ACF components and subsequent fields that could possible exist on a page? And presumingly, any future ACF components I create in the backend of WordPress will need to have there fields added to that same query too? Is that right?

Or is there some way to determining what fields are on the page and dynamically rendering those? I understand graphQL insists I need to be specific on the data returned, and there's no catch all wild card. I just kinda feel that query would be massive and difficult to maintain. 

In an ideal world I would like to be able to simply query and get all the ACF components on the page, loop through and spit them out in the template to dynamically render there respective Vue components. 

I guess the big question I have is....is this even possible?

Forgive me if I have not fully understood certain things, or I'm approaching this in the completely wrong way. Gridsome just looks like an awesome bit of tech, which I'd love to be able to use for my future projects.

**Comment by hacknug** [comment]
> Does this mean in my page template I would need to query all the ACF components and subsequent fields that could possible exist on a page?

I'd say yes but look at it in a simpler way. You're fetching an array of flexible blocks and looping over the items. Then depending on the type of block, you'll use a component or another (always passing down the block contents as props).

> And presumingly, any future ACF components I create in the backend of WordPress will need to have there fields added to that same query too? Is that right?

Yes. Just make sure you check you support that block type or have some kind of fallback (could be ignoring those blocks or filtering them out beforehand).

> Or is there some way to determining what fields are on the page and dynamically rendering those?

As mentioned, just check the type of block you're dealing with when looping over them.

> I just kinda feel that query would be massive and difficult to maintain.

More than a monolithic WordPress codebase? :wink: It's probably going to be the same since you'll loop over the flexible content blocks and do whatever depending on its type/layout.

> In an ideal world I would like to be able to simply query and get all the ACF components on the page, loop through and spit them out in the template to dynamically render there respective Vue components.
> 
> I guess the big question I have is....is this even possible?

Anything concrete that's keeping you from doing that? I mean, you can add your own endpoints to the WordPress API if you don't like what your plugins or theme are exposing. Then you can write your own Gridsome plugin to deal with that data if core's WordPress plugin doesn't handle your case automagically.

If you don't like querying for subfields, you may be able to expose a JSON string on the API and parse that on your component.

----

I hope this was at least somewhat helpful.

**Comment by owenclivee** [comment]
Thank you, that was really helpful! Great to know it's possible and now have done direction 😊👌.

**Comment by zacnomore** [comment]
Closing as resolved by @hacknug
