### ISSUE TITLE
Union type together with Data Store API

### ISSUE THREAD

**Issue by HCl-not-HCi** [gridsome/gridsome#1042]
I'm currently building a website using gridsome which requests data from strapi using the Data Store API. In strapi, there are Dynamic Zones which are composed of different components. These Dynamic Zones are represented by a JSON array (in this case called `Content`). The components are distinguished with the `__component` property.

This is the response from strapi when requesting an article for example (simplified):
```json
{
    "Title": "Testarticle",
    "Content": [
        {
            "__component": "content.rich-text",
            "text": ""
        },
        {
            "__component": "content.slider",
            "Slide": []
        }
    ]
}
```
This results in the following auto generated GraphQL schema in gridsome when using the Data Store API:
```
type Article implements Node {
    title: String
    content: {
        text: String
        slide: []
    }
}
```
You can see that the auto generated schema does not correctly represent the `Content` field because the fields of both components (RichText and Slider) are merged. Because of this, I want to use union types in gridsome so that I have a `union Content = RichText | Slider` as type for the `Content` field.

 I already defined the following schema using the Schema API (I omitted the Slider component):
```JavaScript
actions.addSchemaTypes(`
    type Article implements Node {
        id: ID!,
        title: String,
        content: Content
    }
    type RichText {
        id: ID!,
        text: String
    }
`)

actions.schema.createUnionType({
    name: 'Content',
    types: [ 'RichText' ]
})
```
But I also need a resolver to parse the response from strapi correctly.

And here comes the problem: I'm not sure how to build a resolver for unions and no matter how I build the resolver for the `Content` field, I get the error `Type with name "Content" does not exists` which probably occurs because I used `actions.schema.createUnionType` to define the type `Content`. To me, it seems like it is not possible to add a resolver for union types. I'm not sure whether my whole approach in gridsome is correct at all. So is there a way to solve this problem?

**Comment by amxmln** [comment]
I’m not sure if this is still relevant since this issue is quite old already, but since I’ve just also stumbled over this, I thought I’d pitch in with what I found out:

It is not possible to add a custom resolver for `__resolveType` with `addSchemaResolvers` because the of the error described in the initial report (this is true for Union Types as well as Interfaces in general).

However, I’ve found a workaround. Since the `schema.createUnionType`-Method looked pretty much like the class described [here](https://graphql.org/graphql-js/type/#graphqluniontype) I figured it would be worth trying to add a `resolveType`-Method there—and yay, it works.

So in the OP’s case this _should_ work:

```js
    addSchemaTypes([
      schema.createUnionType({
        name: 'Block',
        types: ['RichText', 'Slider'],
        resolveType(obj) {
          if (obj.__component === 'content.rich-text') return 'RichText';
          if (obj.__component === 'content.slider') return 'Slider';
        },
      }),
    ]);
```
I’m wondering now, whether this is just something that should be documented, or whether this is a hack and I shouldn’t be doing it, because it might break in the future. If the latter is the case, what’s the “official” solution for a case like this?

I feel like a lot of users trying to implement some sort of modular content system for their sites will run into this sooner or later.

**Comment by HCl-not-HCi** [comment]
Thank you, your solution works!

Didn't have the time to look at this in the last months but just gave it a try and it worked.

It seems like this is the correct solution for the problem although it isn't documented in the gridsome docs (the fact that the function is [wrongly documented](https://gridsome.org/docs/schema-api/#schemacreateuniontypeoptions) makes it worse, I almost gave up on this).

But an answer from the devs would be nice to clarify this...

**Comment by sagrawal-idrc** [comment]
Thank you @amxmln the solution works for me as well!

**Comment by sagrawal-idrc** [comment]
Thanks @amxmln , the solution works! I would tend to think that this is a common requirement, as I had the exact same use case working with a different headless cms (prismic, using their "slices" feature).

**Comment by noxify** [comment]
I close this issue for now, feel free to reopen :)
