### ISSUE TITLE
How to filter by null values in a GraphQL query

### ISSUE THREAD

**Issue by tyrion** [gridsome/gridsome#1053]
## Description

I cannot manage to filter by null / not null in a GraphQL query and I am starting to wonder if it is possible at all.

### Steps to reproduce

Here is what I tried (using the gridsome starter blog ):
```
{
  allPost(
    filter: {
      series:{ eq: null }
    }
  ) {
    edges {
      node {
        title
        series
      } 
    }
  }
}
```
The query produces zero results even if there are entries with the field set to null.
I also tried `series: null`, but no filter is applied and all elements are returned.

Am I missing something obvious or is this a bug / missing feature?
Thank you

### Environment

I tried with gridsome v0.7.12 and v0.6.9

Binaries:
    - Node: 12.16.1
    - Yarn: 1.22.0
    - npm: 6.13.4

**Comment by volkipp** [comment]
I also hit this same wall. You could patch around it with a custom resolver, but that gets a little messy. MongoDB has a [filter for existence checks](https://docs.mongodb.com/manual/tutorial/query-for-null-fields/#faq-developers-query-for-nulls) e.g.`allPost(filter: { series: {exists: false}})`. This seems like it would be a nice addition to Gridsome filters as well unless there is already a way to do this.

I could see this being helpful since some CMS sources like Strapi will set all optional unset fields as null, even boolean values. It would be nice to know if the fields are set with a boolean, or if the field wasn't specified with a null value.

**Comment by marcvangend** [comment]
YMMV, but for int fields, `null` seems to be comparable to negative infinity. So If you know (at least roughly) what the lowest value will be, you can use that to your advantage. 

For example, my nodes have an optional "position" value which I never expect to be less than -10. Applying `filter: { position: { gt: -99 }}` filters out the null values, but keeps the valid values with room to spare.

**Comment by cco3** [comment]
@volkipp 

```
Note that any fields you add via custom resolvers will not work in the filter portion of GraphQL queries. This is a gap in Gridsome's GraphQL implementation and will be fixed before Gridsome's 1.0 release.
```

https://gridsome.org/docs/schema-api/

**Comment by ricardov03** [comment]
I found a solution. Reading the comments by @marcvangend, i found that Int values can be filtered by lt: 0 value.
So, you can try this and should return the null values for you:
```javascript
{
  allPost(
    filter: {
      series:{ lt: 0 }
    }
  ) {
    edges {
      node {
        title
        series
      } 
    }
  }
}
```

**Comment by noxify** [comment]
I close this issue for now, feel free to reopen :)
