### ISSUE TITLE
Template routes have name '*' and thus fail to prefetch

### ISSUE THREAD

**Issue by fl0cke** [gridsome/gridsome#1057]
## Description

I'm using the vue-remark plugin to generate pages based on some template. However, i observed that link prefetching does not work with those pages. After digging into the code, i found that all routes generates by the plugin have their name set to `*` which causes prefetching to fail. This is due to the following statement in https://github.com/gridsome/gridsome/blob/7a48f0c81c1b5ae870cc6b06190d53936553baa9/gridsome/app/fetch.js#L52 which falls back to the NOT_FOUND_PATH when the route name is `*`.

I see two options to fix this:

- Automatically assign every route generated by a template a unique name
- Don't default to NOT_FOUND_PATH when the route name is `*`

What do you think?

### Environment
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    gridsome: ^0.7.0 => 0.7.13
    gridsome-plugin-tailwindcss: ^2.2.43 => 2.2.43

**Comment by fl0cke** [comment]
Closing because i found the actual problem, which was totally different to what i described here.
Opening a PR soon!

**Comment by silasabbott** [comment]
What was your solution?

May or may not be related, but I noticed Gridsome is not generating route names for any of my routes except for **index.vue** with the name `home` and **404.vue** with the name `*`.

I noticed this was happening while using [gridsome-plugin-gtm](https://gridsome.org/plugins/gridsome-plugin-gtm) because any unnamed routes were not sending page view events to Google Tag Manager.
