### ISSUE TITLE
g-link doesn't work when navigating from template in production

### ISSUE THREAD

**Issue by AMFTech512** [gridsome/gridsome#1205]
## Description

When I freshly navigate (by refreshing or pasting the url) to a template path (e.g. `/blog/:id` where project contains `/src/templates/BlogPost.vue` and gridsome.config.js is configured to `templates: { BlogPost: '/blog/:id' }`), the template loads, but clicking on g-links doesn't work. **Note**: this problem only occurs when the project has been built for production.

### Steps to reproduce

Clone this repository:
https://github.com/AMFTech512/austinfay-gridsometest

run `npm install`
run `gridsome build`
go into the `dist` directory and start a simple http server. I used http-server available from npm.
Navigate to `http://localhost:8080/blog/7276d4ef759b5f50407ed8829c5ac817`
Click on any link on the page.

### Expected result

The app should navigate to a different page.

### Actual result

Though the route in the url bar changes, the rendered HTML on the page doesn't change. The original blog post template remains the thing that is rendered.

**Comment by noxify** [comment]
Hi,

it seems there is a problem with your `g-link` definition inside the `templates/BlogPost.vue`.
Also the `:key` definition wasn't correct.

I have changed it locally to this one:

```
<template>
    <Layout>
        <h1>Blog Posts</h1>
        <ul>
            <li v-for="blogPost in $static.posts.edges" :key="blogPost.node.id">
                <g-link :to="blogPost.node.path">{{ blogPost.node.title }}</g-link>
            </li>
        </ul>
    </Layout>
</template>

<static-query>
query{
  posts: allBlogPost{
    edges{
      node{
        id
        path
        title
        description
        content
      }
    }
  }
}
</static-query>

<style>

</style>
```

To test the `gridsome build` result, I use this ( just add it to the `scripts` inside the `package.json? ) - I was able to click any link.

```
"prod": "python3 -m http.server --directory dist/"
```

**Comment by noxify** [comment]
Hey @AMFTech512 

Can you reproduce the error with a different host like vercel or netlify?

**Comment by AMFTech512** [comment]
Hi again, @noxify,

Sure. Here's the link:
https://xenodochial-gates-fac98e.netlify.app/

I also updated the code in the repository that I sent you before.

Thanks for taking the time to look at this!

**Comment by noxify** [comment]
Hey @AMFTech512 ,

I'm sorry but I can't reproduce your described problem.

My Env:

* Google Chrome Version 83.0.4103.61
* macOS Catalina 10.15.5

STRs:
1. Open the netlify url in a new tab
2. opened dev tools and ensured that "Network > Disable cache" is disabled
3. Refreshed the website
4. clicked every link
4.1. from each blog post entry i clicked also the "About" and the "Home" link

I have repeated all steps in porn mode, but the result was the same.

Since the OS should not be the problem - Which browser are you using?

Regards,
marcus

**Comment by AMFTech512** [comment]
Hi again, @noxify,

I've tried on 3 browsers:
- Google Chrome Version 83.0.4103.61
- Microsoft Edge Version 83.0.478.44
- Firefox Version 77.0

I'm running Windows 10 Version 1909 Build 18363.836 (but I agree that OS shouldn't matter).

So you don't experience the same behavior? Here's a short video of what I see:
https://drive.google.com/file/d/1HrVwPqm7AcQXc7m6tsDwpJFSd6gbdt5J/view?usp=sharing

Sorry, I really hope I'm not wasting your time.

Austin

**Comment by noxify** [comment]
Hi @AMFTech512 

You’re not wasting my time :) we are here to help 😊

I will check it tomorrow - maybe I have missed something 🤷🏾‍♂️

Thanks for the video :)

**Comment by noxify** [comment]
Hi @AMFTech512 

with your video, I was able to reproduce the issue.
It seems that this issue occurs only if on "BlogPost" pages.

I refreshed the page also on "Blog" and "About", but here the page changed as expected.

**Comment by noxify** [comment]
I did some research on the existing gh issues, I have found multiple issues for this case, but #337 seems to be the same issue.

The problem is, that you have a `p` tag inside a `p` tag.

![image](https://user-images.githubusercontent.com/521777/83612189-5e05ee80-a582-11ea-8e24-f4c18419aff0.png)

Changing the parent `p` to a `div`, it should solve the issue ( original solution: https://github.com/gridsome/gridsome/issues/337#issuecomment-478281759 )

**Comment by AMFTech512** [comment]
Hey @noxify, you're right!

I know that you shouldn't have nested `p` tags, but I also think it's strange that having them causes this behavior in the app. Switching that tag to a `div` definitely solved the problem. 

I can't believe that I didn't find post #337 before... I guess I didn't search hard enough. I was convinced there was a bug in Gridsome.

Thanks for all of your help!

Austin
