### ISSUE TITLE
V-if breaks gridsome in production

### ISSUE THREAD

**Issue by EmmyMay** [gridsome/gridsome#1231]
using `v-if` instead of `v-show` causes a render error where the console throws a 'failure to append child on Node error'

Changing to v-show breaks everything. 

code is here https://github.com/EmmyMay/my-blog

**Comment by Sergix** [comment]
In which file in your repository are you using `v-if`/`v-show`?

**Comment by EmmyMay** [comment]
On the 'develop' branch in src/pages/index.vue

**Comment by EmmyMay** [comment]
Thanks for the reply

**Comment by tkhquang** [comment]
@EmmyMay  Using v-if with a `$vuetify.breakpoint` breaks with SSR. Since `v-if` removes the DOM element (making the mismatch happen between client and server, while using a `v-show` would do since the DOM element remains, but is hidden), Wrapping those `v-if` inside `[<ClientOnly></ClientOnly>](https://gridsome.org/docs/assets-scripts/#without-ssr-support)` would be another solution as well.
