### ISSUE TITLE
Allow for future posting by date.

### ISSUE THREAD

**Issue by ramsesgarate** [gridsome/gridsome#1233]
I would like to propose the ability to schedule publications, that is, what can be established that a publication will be published on June 20 at 08:00 UTC, I do not know how complicated it can be.

Greeting!

**Comment by hjvedvik** [comment]
You can filter nodes based on dates using the [`api.onCreateNode()`](https://gridsome.org/docs/server-api/#apioncreatenodefn) hook. So that pages will not be generated for nodes that have a date future date. But you would need to trigger the build manually. If you pull data from a CMS and want it to automatically publish future posts, then you need to look into something like, for example, [Build hooks](https://docs.netlify.com/configure-builds/build-hooks/) for Netlify. And make the CMS trigger a new build when a post need to be published.

**Comment by ramsesgarate** [comment]
Amazing, that's what I need, thank you very much
