### ISSUE TITLE
Issues with linking to internal pages

### ISSUE THREAD

**Issue by akontra** [gridsome/gridsome#1292]
## Description

I'm having issues with the internal linking in my gridsome project. When I open the site and click a link to an internal page it doesn't work. Once I open the same link in a new tab that instance then works as it should,following links without issue. Same issue on multiple browsers and with multiple users. 
Additionally the links work if I refresh the page after clicking but only if I refresh after every click.

Gridsome does not raise issues at build. (Built and deployed with netlify)

### Steps to reproduce

https://affectionate-brahmagupta-a5154b.netlify.app/      <== the site in question

### Config
gridsome, tailwind css (without plugin), purge css, self hosted fonts

**Comment by akontra** [comment]
> multiple

other

**Comment by hjvedvik** [comment]
This usually happens if there is an error in the generated HTML code. One common mistake which can result in invalid HTML is when using `v-html` on a `<p>` tag. Because the HTML string might include tags that are not allowed in a `<p>` tag. Based on your markup, it looks like the issue can be in the list items inside `<section name="Kontakt">` somewhere. If that's the case, then the easiest solution is to change the `<p>` tag into a `<div>`.

**Comment by akontra** [comment]
Thank you @hjvedvik! I overlooked this while troubleshooting. Fixed the tags and now the site works properly.
