### ISSUE TITLE
Gridsome Graphql not updating in production

### ISSUE THREAD

**Issue by mangomkt** [gridsome/gridsome#1344]
## Description

I am using Graphql to get my data from the firestore...it is working well on production... if I update the store it updates instantly. But when I put it to production and build it ... then it fails to do the updates though the firestore database has been updated.... is there a graphql cache I can turn off? Or is it because I am using a page-query?!?

But like I said it works as expected in develop

**Comment by hjvedvik** [comment]
Data from `page-query` results are cached as static JSON files in production because the GraphQL layer is only available in development. That is probably why it doesn't update. You either need to trigger a new build when something changes in Firestore or connect and fetch the data client-side instead.

**Comment by mangomkt** [comment]
@hjvedvik Is it possible to trigger a new build when I save data?

**Comment by hjvedvik** [comment]
It depends on where you build your site. Netlify, for example, have a guide for how to trigger builds [here](https://docs.netlify.com/configure-builds/build-hooks/). Other services most likely have something similar. I haven't used Firestore much, so I'm not very familiar with it, but it looks like there are some docs [here](https://firebase.google.com/docs/functions/firestore-events) that you can look into in order to send a request to your build service.

**Comment by Sergix** [comment]
Closing since GraphQL client-side fetching is unsupported.
