### ISSUE TITLE
[Question] How to get/guarantee final absolute image URL?

### ISSUE THREAD

**Issue by mzhukovs** [gridsome/gridsome#1364]
I am looking to get the final resting place of the actual image on the server within the code itself, e.g. to be able to set og:image meta I need the absolute URL of the image... but of course any files will get webpacked and end up with some hash stuff in the filename - what is the best way to do this? Would appreciate any insight.

**Comment by MarcelloTheArcane** [comment]
Use `metaInfo`: https://gridsome.org/docs/head/#add-head-meta-data-to-pages--templates

**Comment by Gregordy** [comment]
Hi mate,

You should be able to use the final website url by using Gridsome metadata with

    this.$static.metadata.siteUrl

Thus, if you have an image in your "static" folder you could link it this way

    this.$static.metadata.siteUrl + 'my-beautiful-image.jpg'

Also, don't forget that you should declare your metainfo this way

    metaInfo() {
        return {
            meta: [
                { property: "og:image", content: this.getOgImage() },
                { property: "og:image:secure_url", content: this.getOgImage() }
            ]
        }
    }
 
Using `metaInfo() return {}` instead of `metaInfo {}`

In another case (that could be useful in the future or so), if you are trying to get the absolute path of a local image (as opposed to one that would be fetched from an API) from a template, this is how I was able to make it work:

    require('~/assets/img/waw.jpg')

Here my image is located in `src/assets/img/waw.jpg`

**Comment by mzhukovs** [comment]
Hey thank you very much for the write-up. Seems I was getting confused...  my issue is that the final path to the images contains a hash of some kind (I assumed this was gridsome using webpack behind the scenes, I am new to this framework so apologies)...

Hence, the links to what I'll call the "regular" paths don't work for the meta data image URL.

Getting the images to render using the regular paths in html/vuejs works just fine. However, the end path to that image ends up having a hash in it, e.g. static/logo.png becomes assets/static/logo._cbda223.8e6b09c13687e552668dfb7f2c0eb5f9_.png

But as you've pointed out, just pointing directly to the site URL + the image name (no assets/static path) works just fine...

**Comment by Gregordy** [comment]
You're very welcome! 😄 

Ah yeah I got it, when you say end path, you mean the one that your image has when you try to access it after your site has been built and published.

I'm not that much of a pro regarding this either but I guess that this hash is added by the CDN you use for your website to perform cache invalidation when you publish a new version of your site.

As the filename stays the same, it needs a way to be able to refresh your assets when you deploy a new version. Or maybe it's Gridsome that generates it for each build that it creates.
