### ISSUE TITLE
Handling 404 on a server on page refresh

### ISSUE THREAD

**Issue by kwiat1990** [gridsome/gridsome#1402]
Hi,

I have noticed that my production build have some problems on the server while handling 404. If some route doesn't exist then the Gridsome's custom 404 page will be displayed. If the user make a page refresh on this page, then the page will be served directly from the server (it's pretty straightforward). 

I use shared hosting and I read that to fix this behavior the `.htaccess` file needs to be adjusted. So I've added `FallbackResource /index.html`, which only partially works. As soon as the user make page refresh on any route which gives 404 error, he will see custom Gridsome's 404 page. So far so good. But if he wants to navigate from there, the URL will change but still the custom 404 page will be displayed. In this case only page refresh work and will load the the right page template. The very same behavior exists with the older variant of `FallbackResource`, i.e. `rewrite-mod` (https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations) as well.

It seems that only with `ErrorDocument 404 /404.html` I could manage to fix this behavior.

I would like to understand why the general solution doesn't work as intended. Perhaps someone have experiences this problem as well.

Btw. I don't know how this case is handled on Vercel but if my site is served on that platform I have any problems with 404. It work the same like on my server with this `ErrorDocument 404 /404.html` snippet.

**Comment by hjvedvik** [comment]
@kwiat1990 Fallbacking to `/index.html` works best for SPA, where the markup is rendered client-side. Gridsome pre-renders the HTML-files at build-time, so `/index.html` contains markup for `src/pages/index.vue`. And it usually causes hydration issues because the markup doesn't match the page it tries to render, the 404-page. The`/404.html` is a pre-rendered 404-page and is a better choice for static site generators like Gridsome. I'm not sure about Vercel, but Netlify, for instance,  redirects to the `/404.html` file for all paths that don't' resolve to a static file.

**Comment by kwiat1990** [comment]
Perhaps it should be pointed in the documentation. I have spent some time in order to solve this one :)
