### ISSUE TITLE
Click on current active link should scroll to top

### ISSUE THREAD

**Issue by koronowicz** [gridsome/gridsome#1540]
### Use case

When I'm on route /about/ and in footer of the page I have anchor to the current page. Clicking on it doesn't do anything. 
I think it could be confusing fo the user, so I want it to scroll to the top of the page in that situation. 

## Solution

I wanted to bind it to router like this:
`  router.options.scrollBehavior = function(to, from , savedPosition) {
    return {x: 0, y: 0}
  }`

but it doesn't work. On current route, Vue router is not executed. What are my other options?

**Comment by cameronrr** [comment]
The usual routing behaviour is not executed to prevent duplicate navigation to the current route. Here is one approach to consider:

1. Create a Vue plugin, perhaps src/plugins/scrollActiveLink.js, with the code below
2. Import this file into main.js i.e. import '@/plugins/scrollActiveLinks.js'
3. It will attach a scroll to top for clicks on exact active links.

```javascript
import Vue from 'vue'

class ScrollActiveLinksPlugin {
  install(Vue) {
    if (process.isClient) {
      Vue.mixin({
        mounted() {
          this.$nextTick(() => {
            const activeLinks = document.querySelectorAll(
              'a.active--exact.active'
            )

            const scrollToTop = function () {
              window.scrollTo({ top: 0, left: 0, behavior: 'smooth' })
            }

            activeLinks.forEach((element) => {
              element.addEventListener('click', scrollToTop)
            })
          })
        },
      })
    }
  }
}

Vue.use(new ScrollActiveLinksPlugin())
```

**Comment by cameronrr** [comment]
I've often thought about doing this. I replied a little too soon earlier before testing it fully. But here are some approaches I've come up with now which seem to be working well. They're not fully tested or optimised, but they all seem to work in my limited tests as proof of concept, so can be improved, optimised and tweaked as needed.

## Option 1 - Vue Plugin - Automatically for all g-links
This will check all components, and if its root element is 'a' (i.e. g-link or anchor) then attach a scroll to top click handler.

1. Create a Vue plugin, such as src/plugins/scrollActiveLink.js, with the code below
2. Import this file into main.js i.e. import '@/plugins/scrollActiveLinks.js'
3. Any g-link components for the current route (i.e. a.active.active--exact) will scroll to top.

```javascript
import Vue from 'vue'

class ScrollActiveLinksPlugin {
  install(Vue) {
    if (process.isClient) {
      Vue.prototype.$applyActiveLinkHandlers = function (element) {
        if (element?.matches && element.matches('a.active--exact.active')) {
          element.addEventListener('click', () =>
            window.scrollTo({ top: 0, left: 0, behavior: 'smooth' })
          )
        }
      }
      Vue.mixin({
        mounted() {
          this.$applyActiveLinkHandlers(this.$el)
        },
        updated() {
          this.$applyActiveLinkHandlers(this.$el)
        },
      })
    }
  }
}

Vue.use(new ScrollActiveLinksPlugin())
```

## Option 2 - Vue Plugin - Function to be used as a click handler
Create a function which you can call in click handlers from any component, that will scroll to top if the click target is an active link i.e. link for the current path.

1. Create a Vue plugin, such as src/plugins/scrollActiveLink.js, with the code below
2. Import this file into main.js i.e. import '@/plugins/scrollActiveLinks.js'
3. Use it on g-link components like this `@click.native="$scrollToTopIfActive"`

```javascript
import Vue from 'vue'

class ScrollActiveLinksPlugin {
  install(Vue) {
    if (process.isClient) {
      Vue.prototype.$scrollToTopIfActive = function (event) {
        if (event.currentTarget.matches('a.active--exact.active')) {
          window.scrollTo({ top: 0, left: 0, behavior: 'smooth' })
        }
      }
    }
  }
}

Vue.use(new ScrollActiveLinksPlugin())
```

## Option 3 - Create a Link component to wrap g-link and anchors
Use a custom link component to add more features to your links, like by default, scrolling active links to top. It can also be good to set other default behaviour i.e. rel noopener for new tabs.

1. Create a component to use instead of g-link or a directly, such as the following.
2. Apply some default behaviour to ensure links scroll to top. You could disable this if needed for any links.

```Vue
<template>
  <g-link v-if="to" :to="to" v-bind="attributes" @click.native="scrollTop">
    <slot />
  </g-link>
  <a v-else :href="href" v-bind="attributes" @click="scrollTop">
    <slot />
  </a>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'Link',
  props: {
    to: {
      type: [String, Boolean],
      default: false,
    },
    href: {
      type: [String, Boolean],
      default: false,
    },
    title: {
      type: [String, Boolean],
      default: false,
    },
    newTab: {
      type: Boolean,
      default: false,
    },
    rel: {
      type: [Boolean, String],
      default: false,
    },
    scrollToTopIfActive: {
      type: Boolean,
      default: true,
    },
  },
  computed: {
    target() {
      return this.newTab ? '_blank' : false
    },
    relationship() {
      let relationship = this.rel
      if (this.newTab && this.href) {
        if (!relationship || !relationship.length) {
          relationship = 'noopener'
        }
        if (!relationship.includes('noopener')) {
          relationship += ' noopener'
        }
      }
      return relationship
    },
    attributes() {
      return {
        title: this.title,
        target: this.newTab ? '_blank' : false,
        rel: this.relationship,
      }
    },
  },
  methods: {
    scrollTop(event) {
      if (
        this.scrollToTopIfActive &&
        event.currentTarget.matches('a.active--exact.active')
      ) {
        window.scrollTo({ top: 0, left: 0, behavior: 'smooth' })
      }
    },
  },
})
</script>
```

**Comment by koronowicz** [comment]
Thank you! That's very helpful!

I went for Option 1, less code. We'll test this through.

**Comment by cameronrr** [comment]
@koronowicz Awesome, I have added this feature to one of my sites now also and it is a much better experience when browsing. I use to just set the cursor/pointer to default so it didn't appear clickable! But I am glad your question prompted me to do this better as I had always wanted to address it. Hope you are having success with this.
