### ISSUE TITLE
v-html on built website

### ISSUE THREAD

**Issue by TheoCouss** [gridsome/gridsome#1552]
## Description

On v-html attribute, when I try to output some html from a static query the whole website becomes not interactive.
Links are also not working but i have no update on my screen

On development, everything works, this only happens on built files

I have this issue on many other pages in my project, always the same scheme
-> Static query that queries html content
-> Print it using the v-html attribute

### Steps to reproduce

Make a simple page which queries the html content of a cms then print the result using the v-html attribute

Here's my code
```
<div  v-for="(agenda, index) in $static.agenda" :key="index" :class="{ 'mt-0' : (index == 0) }" class="col">
    <div class="container">
    <div class="row  d-flex flex-xs-row flex-column flex-sm-row bg-light">
        <div class="col mw-90 m-0 p-0">
        <div class="date-sm">
            <div class="date-content">
            <p class="date date-number">{{ agenda.date | moment('DD') }}</p>
            <p class="date date-month">{{ agenda.date | moment('MMM') }} </p>
            <p class="date date-year">{{ agenda.date | moment('YYYY') }} </p>
            </div>
        </div>
        </div>
        <div class="col d-flex flex-column align-items-start p-3 px-sm-4 py-sm-3 fw-medium">
        <h5> {{ agenda.title }}</h5>
        <p class="lh-sm m-0 ps-2 ps-md-0">
            <span v-html="agenda.content"></span>
        </p>
        </div>
    </div>
    </div>
</div>
```

### Environment

  System:
    OS: Linux 4.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
  Binaries:
    Node: 16.4.1 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.18.1 - /usr/bin/npm
  npmPackages:
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4
    gridsome: ^0.7.0 => 0.7.23
    gridsome-source-graphql: ^1.0.2 => 1.0.2

**Comment by cameronrr** [comment]
The issue is most likely that there are invalid HTML tags inside `<span v-html="agenda.content"></span>`. 

If there are elements like `<div>` or `<p>` in `agenda.content` this can be the cause as it's not really valid HTML. 

The reason links don't work is that if the HTML is invalid, the Vue hydration can fail, leading to routing issues.

Can you show an example of the HTML being inserted i.e. example values of `agenda.content`?

**Comment by TheoCouss** [comment]
`agenda.content` contains
```<p>Dossier inscription <span style="text-decoration: underline;">avant le 10 juin</span>! Vous r&eacute;f&eacute;rez sur ce site, onglet en bas de page.</p>```

I read [this](https://gridsome.org/docs/templates/#add-data-to-a-template), the only difference is that I am using a static query

**Comment by cameronrr** [comment]
I think the issue will be the span tag ultimately contains the p tag, which is not really valid. 

Generally, inline elements may contain only data and other inline elements. You can't put block elements inside inline elements.
_Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements#conceptual_differences_

Span is an inline element, and so it can not contain p which is a block element. This can cause issues with Vue in the final build.

Perhaps try the following which results in hierarchy `div > p > span` or `div > div > p > span` rather than `p > span > p > span`

```
<div class="lh-sm m-0 ps-2 ps-md-0" v-html="agenda.content"></div>
```
or
```
<div class="lh-sm m-0 ps-2 ps-md-0">
  <div v-html="agenda.content">
  </div>
</div>
```

**Comment by TheoCouss** [comment]
Thanks a lot for you help!

My final code
```
<div class="lh-sm m-0 ps-2 ps-md-0">
    <div v-html="a.content" />
</div>
```
