### ISSUE TITLE
Gridsome generating ~28 versions per image at build time

### ISSUE THREAD

**Issue by GonzaloHirschToptal** [gridsome/gridsome#1572]
## Summary

We have multiple Gridsome sites, and lately we've been experiencing larger than usual build times (in the minutes, not seconds) in some of our sites. Upon further inspection, we've seen that image processing takes up 90% of the time as it's trying to process thousands of images.

It appears that Gridsome is generating ~28 versions of each of our `src/assets/images` images, probably making our build time 25 times slower (given that other of our sites only generate 3 versions at different resolutions).

I'm guessing this is a configuration from `gridsome.config.js` that we are missing, but the docs doesn't mention anything related to image processing and how to disable/enable some sizes and aspect ratios.

The generated images have different resolutions and aspect ratios, and we'll probably won't ever need as many versions.

### Samples

One of our sites build log:
```
Compile assets - 40.63s
Execute GraphQL (58 queries) - 0.44s
Write out page data (58 files) - 0.01s
Render HTML (58 files) - 0.69s
Process files (0 files) - 0s
Process images (2705 images) - 82.48s
Generate /sitemap.xml (56 pages)
```

**Comment by hjvedvik** [comment]
28 per image seems like a lot. Would you mind sharing the markup for some of the images? Especially for a single image in various places within your project. Just so I can see if we can optimize this somehow :)

**Comment by GonzaloHirschToptal** [comment]
> 28 per image seems like a lot. Would you mind sharing the markup for some of the images? Especially for a single image in various places within your project. Just so I can see if we can optimize this somehow :)

By markup you mean the resolution and aspect ratios, right? For one image I have versions in:
- 480x257
- 480x168
- 800x534
- 400x400
- 200x200
- 500x1000

**Comment by hjvedvik** [comment]
@GonzaloHirschToptal I've been debugging this a bit, but haven't been able to reproduce it. Would you be able to set up a minimal reproduction repo?

**Comment by GonzaloHirschToptal** [comment]
> @GonzaloHirschToptal I've been debugging this a bit, but haven't been able to reproduce it. Would you be able to set up a minimal reproduction repo?

@hjvedvik I set you up a [reproduction repo](https://github.com/GonzaloHirschToptal/gridsome-images-error) with 11 images. From what I gather, each of the `g-image` that loads the image like so:
```
require(`!!assets-loader?width=1440&height=480!@images/${image}`)
```
is generating 3 versions of the image. You'll see on the build log 66 images from those 11 originals.

We have multiple components using `g-image` like that, so I guess that's the cause for so many versions.

Now the questions is, are we doing anything wrong in using the `g-image` like that?

**Comment by hjvedvik** [comment]
@GonzaloHirschToptal  Using the `assets-loader` directly should be okay when you scope it down to a directory or alias like in your example. Just be aware that it will change a bit in the next version of Gridsome because it upgrades to webpack 5 and we had to sort things out a little bit differently.

And thanks for creating the reproduction repo :) I have tried to build it to see if there is anything weird going on. But it seems to work as expected as far as I understand. The images are rendered in two aspect ratios with a maximum width of `1440px`. So Gridsome generates each aspect ratio in `480px`, `1024px` and `1440px`. However, you can control which images sizes you want to generate by passing an `imageWidths` (not documented yet...) query arg to the `assets-loader` like this:

```js
require(`!!assets-loader?width=1440&height=480&imageWidths[]=720&imageWidths[]=1440!@images/${image}`)
```

The example above will generate `720px` and `1440px` instead.

**Comment by GonzaloHirschToptal** [comment]
@hjvedvik thank you for the explanation, I guess we'll start adding these `imageWidths` to reduce our image preprocessing. 

Thanks again!
