### ISSUE TITLE
g-image lazyload blur not working when grab from static folder

### ISSUE THREAD

**Issue by blubMe** [gridsome/gridsome#186]
## Description

i trying to add dynamic image and store it in <g-image /> but when i load the page, the image not blurred first. Then now i just add fake lazyload image 😞 

this is my code :
```html
<div class="preload-img">
   <g-image :src="$page.blogPost.image" />
</div>

<page-query>
  query BlogPost ($path: String!) {
    blogPost (path: $path) {
      image
    }
  }
</page-query>
```

## My Live Example
https://cocky-brattain-5a734f.netlify.com/menjelajah-vue-pengenalan-awal/

Thanks for making  gridsome, I've just migrated my blog from gatsby to gridsome. 💯

**Comment by blubMe** [comment]
### Update

When i try move the image to outside static folder and place it on another folder , Its worked. I dunno why its working.

![screen shot 2019-02-09 at 18 47 43](https://user-images.githubusercontent.com/17546686/52520350-445cdb80-2c9b-11e9-85fe-3cea8bb14cdb.png)

## Sample markdown file
```md
---
title: "Asyncronous pada Javascript"
date: 2019-01-08
image: "./looping.jpg"
slug: asyncronous-pada-javascript
imagedesc: "by Jay Lee @jayleedosis via Unsplash"
---
```

**Comment by hjvedvik** [comment]
Gridsome doesn't process images with paths like `/images/image.jpg` because they are usually located in the `static` folder and those files are just copied to `dist`. The schema currently converts the path into an object with `type`, `src` and `mimeType` but in the next version, it will only return a string. Only image paths like `./images/image.jpg` are processed by Gridsome and that's why you get much more info from the schema.

I hope you enjoyed migrating to Gridsome :)

**Comment by blubMe** [comment]
oh i understand, i forgot to read the README.md on static folder. Thanks for your explanation sir.
