### ISSUE TITLE
Option to change default blur for <g-image>

### ISSUE THREAD

**Issue by tomtev** [gridsome/gridsome#213]
## Summary

The default blur for small `<g-image>` is 40. This is often too much. There should be an option in **config** to change this globally.

We should probably also change the default so something like 15-20.

**Comment by hacknug** [comment]
@tomtev @hjvedvik should we close this issue? I can open a PR with the default blur changes if that's what's keeping you from closing the issue.

**Comment by hjvedvik** [comment]
Yes, I think so, @hacknug. We have probably just forgotten to close this. The default blur can already be configured with a `images.defaultBlur` option in `gridsome.config.js`. But it's not documented yet because the plan is to move the image processing out to a separate plugin with proper documentation.
