### ISSUE TITLE
Drupal starter

### ISSUE THREAD

**Issue by Al-Rozhkov** [gridsome/gridsome#325]
I tested [@gridsome/source-drupal](https://gridsome.org/plugins/@gridsome/source-drupal) plugin and it's just beautiful. If you have functional drupal backend with JSON:API module enabled you can build modern static site in a few minutes. By the way JSON:API goes to Drupal core starting from 8.7 version.

Huge thanks goes to @matt-e-king who is the author of the plugin! And he already start to work on [starter project](https://github.com/matt-e-king/gridsome-starter-drupal).

I suggest to build Drupal starter on top of always available ContentaCMS API: https://back-end.contentacms.io/api

The main advantage is that you have fully functional Gridsome example with flexible and clear content model in just two cli commands. However ContentaCMS has overwritten api keys which is not default for JSON:API module (e.g. `articles` instead of `node--article`).

Lets make Gridsome Drupal starter public and add it to plugin documentation page.

**Comment by matt-e-king** [comment]
Thanks, @Al-Rozhkov! I have no experience or knowledge around ContentaCMS, but I would love some insight on any changes that need to be made to the current [Drupal start project](https://github.com/matt-e-king/gridsome-starter-drupal) to accommodate it.

Regarding this:
> However ContentaCMS has overwritten api keys which is not default for JSON:API module (e.g. articles instead of node--article).

My apologies if I'm misunderstanding, but we built the plugin to work with "overwritten api keys" which you can accomplish with [JSON:API extras](https://www.drupal.org/project/jsonapi_extras) as well. It should theoretically work with anything the jsonapi schema returns. 

@tanc might be able to confirm this since he was our guiding light during development of the plugin, but I believe @tanc tested this plugin with ContentaCMS in mind. 

Again, my apologies if I'm misunderstanding what you are inferring - are you experiencing that it doesn't currently work with ContentaCMS or if we just need to clarify and show examples in the Drupal starter?

Thanks!

**Comment by Al-Rozhkov** [comment]
ContentaCMS is just a drupal distribution with some example content. And yes, it uses [JSON:API extras](https://www.drupal.org/project/jsonapi_extras) to override api keys. Indeed @gridsome/source-drupal handles that perfectly.

I wanted to offer to include ContentaCMS API endpoint to official Gridsome Drupal Starter, like this:
```
{
  use: '@gridsome/source-drupal',
  options: {
    baseUrl: 'https://back-end.contentacms.io',
    apiBase: 'api',
    routes: {
      'articles': '/article/:slug',
      'recipes': '/recipes/:title'
    }
  }
}
```
It is a nice way to play around with Gridsome-Drupal integration without need to set up Drupal backend manually. But I thought It can cause some difficulties for unexperienced users since default keys are little different.

Plugin docs decribes API Schema really well. Probably we can add some helpful comments to `gridsome.config.js` to completely avoid any confusion :smile:

**Comment by matt-e-king** [comment]
@Al-Rozhkov I will update the[ @gridesome/source-drupal](https://github.com/gridsome/gridsome/tree/master/packages/source-drupal) README to have a new table of contents, and I will include a new ContentaCMS section which will elaborate on how ContentaCMS uses JSON:API Extras to override api keys and `apiBase` - but otherwise will work "out-of-the-box".

And as you suggested, in the [Drupal Starter project](https://github.com/matt-e-king/gridsome-starter-drupal) we can also clarify in the README on how to convert the `gridsome.config.js` to work with ContentaCMS.

I'll work on this over the next week, and then send you the pull request to review. How does that sound?

**Comment by Al-Rozhkov** [comment]
Sound awesome 😃 Thank you!

**Comment by matt-e-king** [comment]
@Al-Rozhkov https://github.com/gridsome/gridsome/pull/360

**Comment by Al-Rozhkov** [comment]
I think docs is ready to go. One last thing I can dream of is `gridsome create my-website drupal` CLI command.

**Comment by matt-e-king** [comment]
A CLI command is a good idea! I'm not familiar enough with the whole eco system to know how the [Drupal Starter](https://github.com/matt-e-king/gridsome-starter-drupal) needs to be incorporated in order to scaffold out an app with a CLI command. Someone else would need to be the authority on that.

I believe this ticket can be closed.
