### ISSUE TITLE
g-image loads twice

### ISSUE THREAD

**Issue by markWicht** [gridsome/gridsome#438]
## Description

All g-image load twice, max size and correct viewport size

![Screen-2019-05-17_16-16](https://user-images.githubusercontent.com/38689912/57934203-6d56c300-78bf-11e9-88f3-727739e1c514.png)

### Steps to reproduce

Thoroughly tested, should be easy to reproduce, or some platform/node version issue

`gridsome create gridsome-test`  
Index.vue
`<g-image alt="Example image" src="~/assets/pexels-photo-289586.jpeg" width="1920"/>`  
`img {max-width: 100%;}`  

develop and build versions same result

### Expected result

Only load correct size

### Actual result

Loads twice

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.0, 0.6.0, 0.6.1
- @gridsome/cli version: 0.1.0

Browser:
- [ x ] Chrome (desktop) version 74
- [ x ] Firefox version 68
 
For Tooling issues:
- Node version: 11.8
- Platform:  Windows

Others:
Windows 8.1, npm
</code></pre>

**Comment by dominiquedutra** [comment]
I was able to reproduce this on a clean 0.6 gridsome.
Just added an image on ~/images and linked to it using <g-image> component.
Then, I deployed the website to zeit now.

https://tudocondo-gridsome-wordpress.ddutra.now.sh/image

**Comment by dominiquedutra** [comment]
Hey @hjvedvik @markWicht 

I believe this is not related to Gridsome.

I made a sample page to test srcset loading. You can check it out at https://srcset-playground.ddutra.now.sh/

```
<img src="sample-1280x720.jpg"
           srcset=" 
            sample-3840x2160.jpg 3000w,
            sample-1920x1080.jpg 2000w, 
            sample-1280x720.jpg 1000w, 
            sample-640x480.jpg 700w, 
            sample-300x200.jpg 300w" />
```

Using Chrome 74.0.3729.169 64 bits on MacOS and Chrome Device Simulator.

iPad PRO
![image](https://user-images.githubusercontent.com/4117138/58483069-fed2fa00-8135-11e9-9899-5eadc2e616c8.png)

Pixel 2
![image](https://user-images.githubusercontent.com/4117138/58483111-101c0680-8136-11e9-9c0e-22cdde278d4b.png)

iPhone SE
![image](https://user-images.githubusercontent.com/4117138/58483131-1dd18c00-8136-11e9-8ed6-86d694fc2779.png)

I am further investigating this and will compare the results with the results provided by the tag generated by g-image component.

**Comment by dcastil** [comment]
I had a similar issue with an own implementation of lazy-loaded responsive images about half a year ago. But in my case the image was loaded twice only in Safari for some reason. I still hope that the description of my problem and solution can help here.

In my case I left the `src` and `srcset` attributes empty at first. When intersecting the image, the state in my Vue image component changed so that both `src` and `srcset` were filled with the correct strings. The browser then started downloading the image specified in the `src` attribute, closely followed by downloading the correct image from the `srcset` attribute.

I found out that changing the order of the `src` and `srcset` attributes in my Vue single file component solved the problem:

```vue
<!-- Broken! -->
<img :src="src" :srcset="srcset">

<!-- Working! -->
<img :srcset="srcset" :src="src">
```

The problem was caused by the browser immediately (literally immediately) firing a request if an `<img>` source changes. The `src` attribute was set first, so the browser fired a request to the path specified in there. Afterwards the `srcset` attribute was set and because the `srcset` attribute has precedence over `src`, the image source changed again and the browser fired another request.

So my advice is: Try to make sure that `srcset` is always set and updated before `src`. Hopefully that should resolve it.

**Comment by dominiquedutra** [comment]
I am trying to debug this.

On chrome, it downloads the same image twice:

![image](https://user-images.githubusercontent.com/4117138/58838394-f5192d00-8634-11e9-9b69-511bdf793a43.png)

On firefox, it downloads the correct image and full size image.

![image](https://user-images.githubusercontent.com/4117138/58838455-14b05580-8635-11e9-9b67-a8b8b1842466.png)

The initiators for both images are on gridsome/app/directives/Image.js, lines 77 and 82.

```
function loadImage (el) {
  const src = el.getAttribute('data-src')
  const sizes = el.getAttribute('data-sizes')
  const srcset = el.getAttribute('data-srcset')

  if (!src || el.src.endsWith(src)) {
    return // src is already switched
  }

  const image = new Image()

  image.onload = function () {
    el.classList.remove('g-image--loading')
    el.classList.add('g-image--loaded')
    
    el.src = src //This is the first initiator, If you comment this out you will still get two images
    el.sizes = sizes
    el.srcset = srcset //If you comment el.src = src (above) this will be the first initiator
  }

  image.src = src // This is the second initiator

  el.classList.add('g-image--loading')
  el.classList.remove('g-image--loaded')
}
```

**Comment by robaxelsen** [comment]
@dominiquedutra great work! could you please make a PR out of this, so @hjvedvik can have a look?

**Comment by dominiquedutra** [comment]
@robaxelsen Done.
