### ISSUE TITLE
Can't config proxy in configureWebpack

### ISSUE THREAD

**Issue by thminhVN** [gridsome/gridsome#472]
## Description

I am following config devServer proxy in vuecli

### Steps to reproduce
- Add proxy to webpack config

```
configureWebpack: {
    devServer: {
      proxy: {
        '/.netlify/functions/**': {
          target: 'http://localhost:9000',
          changeOrigin: true,
          secure: false,
          pathRewrite: {
            '^/\\.netlify/functions': ''
          }
        }
      }
    },
  },
```

### Expected result

Should change host

### Actual result

No change host

**Comment by kara-todd** [comment]
I wasn't able to get the webpack devServer proxy to work, but I'm not 100% sure how the gridsome internals worked. Since it looks like [express is used internally](https://gridsome.org/docs/server-api#apiconfigureserverfn), I used a similar approach to creating a [proxy in gatsby](https://www.gatsbyjs.org/docs/api-proxy/#advanced-proxying). This seemed to resolve the issue for me...

### Steps:
1. `yarn add -d http-proxy-middleware` or `npm install http-proxy-middleware --save-dev`
2. Create `gridsome.server.js` in the project root (same directory as `gridsome.config.js`)
3. Add the following code:
```javascript
var proxy = require("http-proxy-middleware");

module.exports = function(api) {
  api.configureServer(app => {
    app.use(
      "/.netlify/functions/",
      proxy({
        target: "http://localhost:9001",
        pathRewrite: {
          "/.netlify/functions/": ""
        }
      })
    );
  });
};
```

**Comment by thminhVN** [comment]
It's worked. Thank you 👍

**Comment by pjatx** [comment]
THANKS for this

**Comment by BobDempsey** [comment]
Tried on 5/22 - Getting error : proxy is not a function. Tried {proxy} as well.

Any help much appreciated! 😀

**Comment by Sergix** [comment]
@BobDempsey 

[The `http-proxy-middleware` package has since been renamed the `proxy` method to `createProxyMiddleware`.](https://github.com/chimurai/http-proxy-middleware#createproxymiddlewareuri--config) You should now import the method like this:

```javascript
const { createProxyMiddleware } = require('http-proxy-middleware')
```

**Comment by OzzyTheGiant** [comment]
> @BobDempsey
> 
> [The `http-proxy-middleware` package has since been renamed the `proxy` method to `createProxyMiddleware`.](https://github.com/chimurai/http-proxy-middleware#createproxymiddlewareuri--config) You should now import the method like this:
> 
> ```js
> const { createProxyMiddleware } = require('http-proxy-middleware')
> ```

This is absolutely true, however at the time of this writing, Gridsome uses version 0.19 of that package so everyone should just import the version available with Gridsome and use the old syntax for now.
