### ISSUE TITLE
Subsequent Gridsome builds causing 404's with JS assets

### ISSUE THREAD

**Issue by timcreatewell** [gridsome/gridsome#488]
## Description

I'm running into an issue with a Gridsome site in production, which is being hosted on Netlify, however I would imagine this issue would affect most hosting providers. 

Specifically, each time Gridsome builds, new JS assets are generated with new cache-invalidation suffixes.  This unfortunately causes issues for users who are already browsing previous versions of the site.  When they attempt to browse to a new page, the browser complains that the necessary JS is no longer available (404) and the routing does not occur.

### Steps to reproduce

1. Deploy your site to your hosting provider (e.g. Netlify).
2. Visit the site in your browser.
3. Re-deploy your site.
4. Return to your browser and try to browse around your site (without refreshing your browser).
5. Things should fail.

I have also been able to reproduce this locally by running `gridsome build` successively and using a local web server.

### Expected result

The site should gracefully recover, perhaps by doing a page refresh??

### Actual result

The site crashes with multiple 404 errors in the console relating to missing JS files.

### Environment

<pre><code>
Libs:
- @gridsome/cli version: v0.0.9
- gridsome version: v0.6.3
</code></pre>

**Comment by dominiquedutra** [comment]
Browser: Firefox Developer Latest with the console open and preserve log ticked
**Deploy to Zeit Now**
Browsed about 10 pages of the website (not counting the infinite scroll background fetching of json files for next pages)
Rebuild and redeployed over the same project

Browsing pages already visited works
Other pages don`t work - I am getting JSON.parse errors instead of 404s - and the page won't load

![image](https://user-images.githubusercontent.com/4117138/59101567-bff42f80-88ff-11e9-8103-b962829eac78.png)

**Comment by josepjaume** [comment]
I believe a good way to tackle this is to capture the exception and resort to a regular `window.location = url` - that'd refresh the entire app.

**Comment by hjvedvik** [comment]
Yes, I've done some testing and a simple fix would be to use `location.assign(to.fullPath)` in `router.beforeEach` whenever a route component fails to load or a JSON file for a page doesn't exist. We'll try to include a fix next time we publish an update :)

**Comment by seangwright** [comment]
Followed a trail of links on the internet to get here and I'm digging into Gridsome, which seems cool!

Just thought I'd mention that Angular (with which I have a fair amount of experience) solves this very issue using service workers.

The service worker downloads the entire app and caches it locally. The user can keep navigating even when a new version of the app (with new asset hashes) is deployed on the server/CDN.

Then the service worker alerts the application that an update is available which can be used to visually prompt the user or programmatically refresh the site.

Meanwhile the new version of the app is downloaded by the service worker and cached so that when the user refreshes the site, the new app is used.

The service worker allows for both version of the app to live cached locally side-by-side so that a user with the old assets can continue to use parts of the app they haven't navigated to yet without errors.

**Comment by hjvedvik** [comment]
@seangwright That behavior is what we want to do with a PWA/offline plugin :) But we haven't got the time to look into it yet...

We are currently only reloading the site if outdated assets or data is detected. I'll close this, but feel free to re-open if anyone still has issues with this.

**Comment by u12206050** [comment]
Just for reference on how I achieved cache busting in vue pwa: [vuejs-pwa-cache-busting](https://medium.com/js-dojo/vuejs-pwa-cache-busting-8d09edd22a31)
