### ISSUE TITLE
Can't find page 1 when use paginate and production build

### ISSUE THREAD

**Issue by isoppp** [gridsome/gridsome#515]
## Description

Can't find page 1 when production build.

When using `paginate` in page-query, I can find page 1 on local server(`gridsome develop`) but I can't find it on production build.

I found it when I want to use original pager component.

### Steps to reproduce

- Use `paginate`.
- Confirm page 1 with 'gridsome develop' on browser.
- Confirm resources which was exported by production build.

### Expected result

Resources which was exported by production build also can access page 1 like developing site.

or

Local site can't access page 1 like resources which was exported by production build.

### Actual result

I can't find page 1 when production build but I can access while I'm developing on localhost.

### Environment

gridsome 0.5.8

Browser: Chrome (but I think it's unrelated)

For Tooling issues:
- Node version: 10.15.1
- Platform:  Mac and Netlify

**Comment by hjvedvik** [comment]
Hi @isoppp :) I think we should return 404 for page/1 in development until we find a good solution for generating it in production. It's possible to create redirects routes in Vue Router, but it doesn't work well for static sites since there is no generated HTML file for that URL. We will have some redirect methods sometime soon that probably will work better.

**Comment by isoppp** [comment]
Hi @hjvedvik :)
I agree with your idea perfectly and thank you for fixing this.
I will confirm and close this issue after it publishes.

**Comment by isoppp** [comment]
Thank you for the fix, I confirmed it :)
I close this.
