### ISSUE TITLE
Add file modified info to source-filesystem plugin

### ISSUE THREAD

**Issue by woubuc** [gridsome/gridsome#579]
## Summary
I'd love to have access to the **last modified time** and **created time** through the `fileInfo` object, for pages loaded with the `source-filesystem` plugin.

This can be done by simply running `fs.stat()` on the file and adding the relevant fields to the generated `fileInfo` object.

I've looked over the other properties on the `fs.Stats` object, but they seem less relevant to me.

### Basic example
```graphql
type PostFileInfo { # Generated FileInfo type (in this case, for a Post type)
  # Existing fields
  extension: String
  directory: String
  path: String
  name: String

  # Proposed additions
  created: Int # stats.birthtimeMs
  lastModified: Int # stats.mtimeMs
}
```

### Motivation
Knowing when a page was last modified is useful information to display, especially on a blog. It can be done by manually updating a page property on every change, but it would be a lot easier and more accurate if the information could be loaded from the filesystem info directly.

**Comment by u12206050** [comment]
@woubuc I doubt this will work once you push deploy to a server since the files 'created' and 'lastModified' dates are then set to the time of deployment.

"Git does not store file creation dates (in a significant sense, Git's files don't have creation dates)."

Might be that in your use case this won't be an issue if you are always deploying from your own server.

So we can not add this sorry. It might work during development but it won't work in production..

**Comment by Edmund1645** [comment]
the best technique could be to add them manually to the front matter.
