### ISSUE TITLE
Netlify Deploy ==> Error running command: Build script returned non-zero exit code: 1

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [gridsome/gridsome#582]
`Grid develop` works fine.

**The Repo:**
https://github.com/Ezra-Siton-UIX/new-siteb-2019

**The error (From netlify deploy):**
```
9:42:50 PM: Build ready to start
9:42:54 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
9:42:54 PM: build-image tag: v3.3.2
9:42:54 PM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
9:42:55 PM: Fetching cached dependencies
9:42:55 PM: Failed to fetch cache, continuing with build
9:42:55 PM: Starting to prepare the repo for build
9:42:55 PM: No cached dependencies found. Cloning fresh repo
9:42:55 PM: git clone https://github.com/Ezra-Siton-UIX/new-siteb-2019
9:42:59 PM: Preparing Git Reference refs/heads/master
9:42:59 PM: Starting build script
9:42:59 PM: Installing dependencies
9:43:01 PM: Downloading and installing node v10.16.0...
9:43:02 PM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
9:43:02 PM: 
###
9:43:02 PM:                    4.5%
9:43:02 PM: 
#####################
9:43:02 PM:                              30.2%
9:43:02 PM: 
#########################################################
9:43:02 PM: #######          89.0%
9:43:02 PM: 
#############################
9:43:02 PM: ########################################### 100.0%
9:43:02 PM: Computing checksum with sha256sum
9:43:02 PM: Checksums matched!
9:43:05 PM: Now using node v10.16.0 (npm v6.9.0)
9:43:06 PM: Attempting ruby version 2.6.2, read from environment
9:43:07 PM: Using ruby version 2.6.2
9:43:08 PM: Using PHP version 5.6
9:43:08 PM: Started restoring cached node modules
9:43:08 PM: Finished restoring cached node modules
9:43:08 PM: Installing NPM modules using NPM version 6.9.0
9:43:41 PM: > sharp@0.22.1 install /opt/build/repo/node_modules/sharp
9:43:41 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
9:43:42 PM: info
9:43:42 PM: sharp
9:43:42 PM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
9:43:44 PM: > core-js@2.6.9 postinstall /opt/build/repo/node_modules/core-js
9:43:44 PM: > node scripts/postinstall || echo "ignore"
9:43:44 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
9:43:44 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
9:43:44 PM: > https://opencollective.com/core-js 
9:43:44 PM: > https://www.patreon.com/zloirock 
9:43:44 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
9:43:45 PM: > cwebp-bin@5.1.0 postinstall /opt/build/repo/node_modules/cwebp-bin
9:43:45 PM: > node lib/install.js
9:43:46 PM:   ✔ cwebp pre-build test passed successfully
9:43:46 PM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
9:43:46 PM: > node lib/install.js
9:43:46 PM:   ✔ mozjpeg pre-build test passed successfully
9:43:46 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
9:43:46 PM: > node lib/install.js
9:43:47 PM:   ✔ pngquant pre-build test passed successfully
9:43:49 PM: npm
9:43:49 PM:  WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
9:43:49 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
9:43:49 PM: added 1289 packages from 667 contributors and audited 17346 packages in 39.458s
9:43:49 PM: found 0 vulnerabilities
9:43:49 PM: NPM modules installed
9:43:49 PM: Started restoring cached go cache
9:43:49 PM: Finished restoring cached go cache
9:43:49 PM: unset GOOS;
9:43:49 PM: unset GOARCH;
9:43:49 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
9:43:49 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
9:43:49 PM: go version >&2;
9:43:49 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
9:43:49 PM: go version go1.12 linux/amd64
9:43:49 PM: Installing missing commands
9:43:49 PM: Verify run directory
9:43:49 PM: Executing user command: gridsome build
9:43:50 PM: Gridsome v0.6.7
9:43:50 PM: Initializing plugins...
9:43:51 PM: Initialize - 0.63s
9:43:51 PM: Load sources - 0.07s
9:43:51 PM: Create GraphQL schema - 0.19s
9:43:51 PM: Create pages and templates - 0.1s
9:43:51 PM: Generate code - 0.06s
9:43:51 PM: Bootstrap finish - 1.05s
9:43:52 PM: An error occurred while executing page-query for src/templates/Post.vue
9:43:52 PM: Error: /opt/build/repo/content/posts/images/mula/2_about.png was not found.
9:43:52 PM: GraphQL request:116:5
9:43:52 PM: 115 |     description
9:43:52 PM: 116 |     content
9:43:52 PM:     |     ^
9:43:52 PM: 117 |     image
9:43:52 PM:     at pMap (/opt/build/repo/node_modules/gridsome/lib/graphql/executeQueries.js:31:13)
9:43:53 PM: Skipping functions preparation step: no functions directory set
9:43:53 PM: Caching artifacts
9:43:53 PM: Started saving node modules
9:43:53 PM: Finished saving node modules
9:43:53 PM: Started saving pip cache
9:43:53 PM: Finished saving pip cache
9:43:53 PM: Started saving emacs cask dependencies
9:43:53 PM: Finished saving emacs cask dependencies
9:43:53 PM: Started saving maven dependencies
9:43:53 PM: Finished saving maven dependencies
9:43:53 PM: Started saving boot dependencies
9:43:53 PM: Finished saving boot dependencies
9:43:53 PM: Started saving go dependencies
9:43:53 PM: Finished saving go dependencies
9:44:00 PM: Error running command: Build script returned non-zero exit code: 1
9:44:00 PM: Failing build: Failed to build site
9:44:00 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
9:44:00 PM: Finished processing build request in 1m5.788194345s
```

**Comment by leopiccionia** [comment]
You have a typo. Image is named `2_About.png`, not `2_about.png`.

**Comment by Ezra-Siton-UIX** [comment]
Wow Thanks! - next time I will read all of this long text. Weird under `gridsome develop` no issue.

**Comment by VolodymyrTesliuk** [comment]
Hello guys, could you give me advice? I need help.
I'm deploying a Vue App to Netlify. But unfortunately it occurs an error

I see the it's some problem with yarn. But I don't know how to solve this.

My yarn version is 1.19.1
Netlify use version 1.17.0

Verifying integrity...
9:30:23 PM: gpg: Signature made Fri 14 Jun 2019 06:55:58 PM UTC using RSA key ID 69475BAA
9:30:23 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
9:30:23 PM: gpg: WARNING: This key is not certified with a trusted signature!
9:30:23 PM: gpg:          There is no indication that the signature belongs to the owner.
9:30:23 PM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
9:30:23 PM:      Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
9:30:23 PM: > GPG signature looks good
9:30:23 PM: > Extracting to ~/.yarn...
9:30:24 PM: > Adding to $PATH...
9:30:24 PM: > We've added the following to your /opt/buildhome/.profile
9:30:24 PM: > If this isn't the profile of your current shell then please add the following to your correct profile:
9:30:24 PM: export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
9:30:24 PM: 
9:30:24 PM: > Successfully installed Yarn 1.17.0! Please open another terminal where the yarn command will now be available.
9:30:25 PM: Installing NPM modules using Yarn version 1.17.0
9:30:26 PM: yarn install v1.17.0
9:30:26 PM: [1/4] Resolving packages...
9:30:27 PM: [2/4] Fetching packages...
9:30:40 PM: error An unexpected error occurred: "https://registry.yarnpkg.com/@vue/babel-preset-jsx/-/babel-preset-jsx-1.1.1.tgz: Request failed \"504 Gateway Timeout\"".
9:30:40 PM: info If you think this is a bug, please open a bug report with the information provided in "/opt/build/repo/yarn-error.log".
9:30:40 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
9:31:37 PM: Error during Yarn install
9:31:37 PM: Error running command: Build script returned non-zero exit code: 1
9:31:37 PM: Failing build: Failed to build site
9:31:37 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
9:31:37 PM: Finished processing build request in 1m31.829752628s

**Comment by Ezra-Siton-UIX** [comment]
@VolodymyrTesliuk It's better to open a new issue (And maybe add a link to this topic). This topic is closed (So fewer users read this).

**Comment by suriya43426** [comment]
Hello guys, could you give me advice? I need help.
I'm deploying a React App to Netlify. But unfortunately it occurs an error

12:36:22 AM: Build ready to start
12:36:27 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
12:36:27 AM: build-image tag: v3.3.2
12:36:27 AM: buildbot version: a2bab682ae0761baa4d123ebd00c57be933655dc
12:36:27 AM: Fetching cached dependencies
12:36:28 AM: Failed to fetch cache, continuing with build
12:36:28 AM: Starting to prepare the repo for build
12:36:28 AM: No cached dependencies found. Cloning fresh repo
12:36:28 AM: git clone https://github.com/suriya43426/Food-Can-Trust
12:36:29 AM: Preparing Git Reference refs/heads/master
12:36:29 AM: Starting build script
12:36:29 AM: Installing dependencies
12:36:30 AM: Downloading and installing node v10.17.0...
12:36:30 AM: Downloading https://nodejs.org/dist/v10.17.0/node-v10.17.0-linux-x64.tar.xz...
12:36:31 AM: 
######################################
12:36:31 AM:  53.1%
12:36:31 AM: 
########################################
12:36:31 AM: ################################ 100.0%
12:36:31 AM: Computing checksum with sha256sum
12:36:31 AM: Checksums matched!
12:36:33 AM: Now using node v10.17.0 (npm v6.11.3)
12:36:33 AM: Attempting ruby version 2.6.2, read from environment
12:36:35 AM: Using ruby version 2.6.2
12:36:35 AM: Using PHP version 5.6
12:36:35 AM: Started restoring cached node modules
12:36:35 AM: Finished restoring cached node modules
12:36:35 AM: Started restoring cached yarn cache
12:36:35 AM: Finished restoring cached yarn cache
12:36:35 AM: Installing yarn at version 1.17.0
12:36:35 AM: Installing Yarn!
12:36:35 AM: > Downloading tarball...
12:36:35 AM: [1/2]: https://yarnpkg.co
12:36:35 AM: m/downloads/1.17.0/yarn-v1.17.0.tar.gz --> /tmp/yarn.tar.gz.4Qe5
12:36:35 AM: KXvwEY
12:36:35 AM:  % Total    % Received
12:36:35 AM:  % Xferd  Average Speed   Time    Time     Time  Current
12:36:35 AM:                       Dload  Uploa
12:36:35 AM: d   Total   Spent    Left  Speed
12:36:35 AM: 
  0     0    0     0    0
12:36:35 AM:    0      0      0 --:--:-- --:--:--
12:36:35 AM:  --:--:--     0
12:36:35 AM: 
100    93  100    93    0     0    447
12:36:35 AM: 0 --:--:-- --:--:-- --:--:--   449
12:36:35 AM: 
  0     0    0     0    0     0      0      0
12:36:35 AM:  --:--:-- --:--:-- --:--:--     0
12:36:35 AM: 
100   609    0   609    0     0
12:36:35 AM:  1032      0 --:--:-- --:--:-- --:--:--  2306
12:36:36 AM: 
100 1213k  100 1213k    0     0  1232k
12:36:36 AM:  0 --:--:-- --:--:-- --:--:-- 1232k
12:36:36 AM: [2/2]: https://yarnpkg.com/downloads/1.17.0/yarn-v1.1
12:36:36 AM: 7.0.tar.gz.asc --> /tmp/yarn.tar.gz.4Qe5KXvwEY.asc
12:36:36 AM: 
100    97  100    97    0     0
12:36:36 AM:    2180      0 --:--:-- --:--:-- --:--:--  2180
12:36:36 AM: 
100   613    0   613    0     0   3800
12:36:36 AM:       0 --:--:-- --:--:-- --:--:--  3800
12:36:36 AM: 
100   832  100   832    0     0   4157      0
12:36:36 AM: --:--:-- --:--:-- --:--:--  4157
12:36:36 AM: > Verifying integrity...
12:36:37 AM: gpg: Signature made Fri 14 Jun 2019 06:55:58 PM UTC using RSA key ID 69475BAA
12:36:37 AM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
12:36:37 AM: gpg: WARNING: This key is not certified with a trusted signature!
12:36:37 AM: gpg:          There is no indication that the signature belongs to the owner.
12:36:37 AM: Primary key fingerprint: 72EC F46A 56B4 AD39
12:36:37 AM:  C907  BBB7 1646 B01B 86E5 0310
12:36:37 AM:      Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
12:36:37 AM: > GPG signature looks good
12:36:37 AM: > Extracting to ~/.yarn...
12:36:37 AM: > Adding to $PATH...
12:36:37 AM: > We've added the following to your /opt/buildhome/.profile
12:36:37 AM: > If this isn't the profile of your current shell then please add the following to your correct profile:
12:36:37 AM: export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
12:36:37 AM: 
12:36:37 AM: > Successfully installed Yarn 1.17.0! Please open another terminal where the `yarn` command will now be available.
12:36:38 AM: Installing NPM modules using Yarn version 1.17.0
12:36:38 AM: yarn install v1.17.0
12:36:38 AM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
12:36:38 AM: [1/4] Resolving packages...
12:36:40 AM: [2/4] Fetching packages...
12:36:55 AM: info fsevents@2.0.7: The platform "linux" is incompatible with this module.
12:36:55 AM: info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
12:36:55 AM: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
12:36:55 AM: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
12:36:55 AM: [3/4] Linking dependencies...
12:36:55 AM: warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
12:36:55 AM: warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
12:36:55 AM: warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
12:37:02 AM: [4/4] Building fresh packages...
12:37:03 AM: success Saved lockfile.
12:37:03 AM: Done in 25.04s.
12:37:03 AM: NPM modules installed using Yarn
12:37:04 AM: Started restoring cached go cache
12:37:04 AM: Finished restoring cached go cache
12:37:04 AM: unset GOOS;
12:37:04 AM: unset GOARCH;
12:37:04 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
12:37:04 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
12:37:04 AM: go version >&2;
12:37:04 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
12:37:04 AM: go version go1.12 linux/amd64
12:37:04 AM: Installing missing commands
12:37:04 AM: Verify run directory
12:37:04 AM: Executing user command: yarn build
12:37:04 AM: yarn run v1.17.0
12:37:04 AM: $ react-scripts build
12:37:06 AM: Creating an optimized production build...
12:37:09 AM: Failed to compile.
12:37:09 AM: ./src/App.js
12:37:09 AM: Cannot find file './App.CSS' in './src'.
12:37:09 AM: error Command failed with exit code 1.
12:37:09 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:37:09 AM: Skipping functions preparation step: no functions directory set
12:37:09 AM: Caching artifacts
12:37:09 AM: Started saving node modules
12:37:09 AM: Finished saving node modules
12:37:09 AM: Started saving yarn cache
12:37:09 AM: Finished saving yarn cache
12:37:09 AM: Started saving pip cache
12:37:09 AM: Finished saving pip cache
12:37:09 AM: Started saving emacs cask dependencies
12:37:09 AM: Finished saving emacs cask dependencies
12:37:09 AM: Started saving maven dependencies
12:37:09 AM: Finished saving maven dependencies
12:37:09 AM: Started saving boot dependencies
12:37:09 AM: Finished saving boot dependencies
12:37:09 AM: Started saving go dependencies
12:37:09 AM: Finished saving go dependencies
12:37:12 AM: Error running command: Build script returned non-zero exit code: 1
12:37:12 AM: Failing build: Failed to build site
12:37:12 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
12:37:12 AM: Finished processing build request in 44.462959762s

**Comment by VolodymyrTesliuk** [comment]
Redeploy helped me. It was easier than I thought.

**Comment by morgansegura** [comment]
What was the issue? When you say redeploy, do you mean from Git or Netlify?

**Comment by Abhatt18-ui** [comment]
Hi guys, place give me advice! I need help.
I'm deploying a React App to Netlify. But unfortunately it occurs an error

8:52:55 PM: Netlify Build                                                 
8:52:55 PM: ────────────────────────────────────────────────────────────────
8:52:55 PM: ​
8:52:55 PM: ❯ Version
8:52:55 PM:   @netlify/build 29.12.1
8:52:55 PM: ​
8:52:55 PM: ❯ Flags
8:52:55 PM:   baseRelDir: true
8:52:55 PM:   buildId: 6487383bc9aafc48a5d31308
8:52:55 PM:   deployId: 6487383bc9aafc48a5d3130a
8:52:55 PM: ​
8:52:55 PM: ❯ Current directory
8:52:55 PM:   /opt/build/repo
8:52:55 PM: ​
8:52:55 PM: ❯ Config file
8:52:55 PM:   No config file was defined: using default values.
8:52:55 PM: ​
8:52:55 PM: ❯ Context
8:52:55 PM:   production
8:52:55 PM: ​
8:52:55 PM: Build command from Netlify app                                
8:52:55 PM: ────────────────────────────────────────────────────────────────
8:52:55 PM: ​
8:52:55 PM: $ CI= npm run build
8:52:55 PM: > techline-client@1.0.0 build
8:52:55 PM: > npm install --prefix client && npm run build --prefix client
8:53:00 PM: npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
8:53:00 PM: npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
8:53:00 PM: npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
8:53:01 PM: npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
8:53:07 PM: added 1626 packages, and audited 1628 packages in 12s
8:53:07 PM: 236 packages are looking for funding
8:53:07 PM:   run `npm fund` for details
8:53:07 PM: 6 high severity vulnerabilities
8:53:07 PM: To address all issues (including breaking changes), run:
8:53:07 PM:   npm audit fix --force
8:53:07 PM: Run `npm audit` for details.
8:53:08 PM: > client@0.1.0 build
8:53:08 PM: > react-scripts build
8:53:09 PM: Creating an optimized production build...
8:54:09 PM: Compiled successfully.
8:54:09 PM: 
8:54:09 PM: File sizes after gzip:
8:54:09 PM:   308.63 kB  build/static/js/main.d03294ef.js
8:54:09 PM:   1.78 kB    build/static/js/787.c4e7f8f9.chunk.js
8:54:09 PM:   264 B      build/static/css/main.e6c13ad2.css
8:54:09 PM: The project was built assuming it is hosted at /.
8:54:09 PM: You can control this with the homepage field in your package.json.
8:54:09 PM: The build folder is ready to be deployed.
8:54:09 PM: You may serve it with a static server:
8:54:09 PM:   npm install -g serve
8:54:09 PM:   serve -s build
8:54:09 PM: Find out more about deployment here:
8:54:09 PM:   https://cra.link/deployment
8:54:09 PM: ​
8:54:09 PM: (build.command completed in 1m 14.8s)
8:54:09 PM: ​
8:54:11 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
8:54:11 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
8:54:11 PM: Failing build: Failed to build site
8:54:11 PM: Finished processing build request in 1m34.359s
