### ISSUE TITLE
Ways to build gridsome project when data source changes

### ISSUE THREAD

**Issue by kororo** [gridsome/gridsome#598]
I like Gridsome including the plugins to connect with lots of existing data source including Worpdress. I just wondering what is the best way to do automatic ```gridsome build``` when the data source (eg. Wordpress posts) change?

Is it advise-able to always build the whole entire pages of data source (eg. Wordpress) because of 1 page changed or there is specific command to select posts to build?

**Comment by dominiquedutra** [comment]
Hey @kororo 
As of now you have to build everything every time, but its really fast so unless you have 10 thousand pages you should't worry. Only problem would be images, but soon we should have a feature that prevents images from being processed again and again on every build (https://github.com/gridsome/gridsome/issues/494).

https://tudocondo.com.br has about 300 pages and it builds really fast.

As of automatically building, there are no triggers for this yet but it should't be hard to implement. As of now I am doing a manual deploy that runs on my macbook and rsync over sftp to my webserver because I require to run this website on my own server but I could as easily do netlify or zeit now. 
I just have to do a `cd ~/Desktop/tudocondo.com.br && ./deploy` every monday and friday morning (days my posts go live) and go grab a coffee. I could of course find a way to make this automatic running on the server itself but I`ve been busy with other things and its so easy. Its also easy to forget!

Automatic triggers would depend on wordpress to trigger the redeploy, or you could monitor your backend. There are actually many ways I can see this done but none implemented yet.

Hope it helps.

**Comment by u12206050** [comment]
Using [Netlify](https://netlify.com) you can toggle a rebuild using a webhook which you can automatically call on post save for example.
Partial builds is not implemented yet but it is being researched.

**Comment by kororo** [comment]
@dominiquedutra @u12206050 Thanks guys for the clarification. I may make something for the Wordpress to make hook and do some auto build. No promise but once it is built and it is worth to share, I will ping you guys.

**Comment by hacknug** [comment]
@kororo there's a few plugins that will do that for you automatically: https://wordpress.org/plugins/search/netlify/

**Comment by kororo** [comment]
@hacknug this looks interesting https://wordpress.org/plugins/wp-jamstack-deployments/

Thanks everyone. I think I will start from that plugin then if my usage is sufficient, I will use it as is. Otherwise, I will post something here.

**Comment by karki-dennis** [comment]
@kororo  Does the plugin you mentioned did the job you want?
