### ISSUE TITLE
404 Config

### ISSUE THREAD

**Issue by xi-osman** [gridsome/gridsome#610]
Tried getting info on discord but still no luck so when I build the website I get 2 404 pages in the dist folder, so it looks like this.
```bash
├── dist
│   ├── 404
│   │   └── index.html
│   └── 404.html
```
dist/404/index.html
dist/404.html

How can I remove the 404 route one? or is this required?

**Comment by hjvedvik** [comment]
The `/404/index.html` file is copied to `/404.html` because many static web hosts look for a `/404.html` file to show the `404` message.

The `/404/index.html` file is just required to make the `/404` route work. But I think we should add the `.html` extension to the "not found" route in Vue router instead to only have one HTML file. It will require some changes in how we generate the HTML files etc. And one good reason to change this is when someone has pagination on the homepage with more than 403 pages :)

**Comment by xi-osman** [comment]
Awesome thanks for the explanation closing this now! 👌
