### ISSUE TITLE
[Question] Nested Routes for Gridsome?

### ISSUE THREAD

**Issue by moritzlaube** [gridsome/gridsome#621]
I am sorry to maybe misuse this repo for a question. But I don't get the answers anywhere else. 

In Gridsome, I am basically looking for Vue's nested route functionality (or Nuxt's child-view) to achieve something like this /:userId/profile and /:userId/posts for example. And since Gridsome uses Vue Router there should be a way to achieve this, I believe?

Let me try to explain what I am trying to build with Gridsome:

At mywebsite.com/ I want to show a Grid of images showing thumbnails of my video portfolio. When you then click on a thumbnail I want a modal to pop-up showing the video. The modal is semi transparent showing the portfolio in the background. So far so good.

But for people to be able to share the URL of the respective video, I need the path changing to mywebsite.com/video-1 and so on. When I then close the modal the path should be mywebsite.com/ again. This is something I already achieved within Nuxt with <child-view>.

Is there some similar functionality in Gridsome? I appreciate your help.

**Comment by hjvedvik** [comment]
Gridsome doesn't support child routes yet. But you can kind of achieve what you want if you create a new content type called `User` and add each user as a node. Then generate pages for them with the [Pages API](https://gridsome.org/docs/pages-api). The pages you create can share a layout component.

In the same way, you can also generate pages for each video for having direct URLs to them. And use the [`$fetch()`](https://gridsome.org/docs/client-api#fetchpath) method to load a video in a pop-up. Or just query the videos in the front-page query instead of using `$fetch()`.

**Comment by moritzlaube** [comment]
> Gridsome doesn't support child routes yet. But you can kind of achieve what you want if you create a new content type called `User` and add each user as a node. Then generate pages for them with the [Pages API](https://gridsome.org/docs/pages-api). The pages you create can share a layout component.
> 
> In the same way, you can also generate pages for each video for having direct URLs to them. And use the [`$fetch()`](https://gridsome.org/docs/client-api#fetchpath) method to load a video in a pop-up. Or just query the videos in the front-page query instead of using `$fetch()`.

That's it! Thanks so much! Still can't wait for the child routes feature. :)
