### ISSUE TITLE
Build failed: Window is not defined

### ISSUE THREAD

**Issue by rinkesh412** [gridsome/gridsome#800]
## Description

When I try to build , I am getting error : Window is not defined. But gridsome develop is working fine. I have added jquery module in default layout . window.jQuery = require('jquery');

Please help me about this issue. 

Thanks

**Comment by hacknug** [comment]
`window` is only available from the client so you need to check for that before trying to do anything with it. Can read more about it on the docs here: https://gridsome.org/docs/client-api/#isclient

**Comment by rinkesh412** [comment]
Thanks for reply. 
So in order to build app, what would I use in place of window ? I just check `process.isClient`  return TRUE.  In what manner, should I use jQuery which will work for me in development and deployment ?

Thanks

**Comment by hacknug** [comment]
Not sure where you're using this or how but something like this might work:

```js
if (process.isClient) {
  window.jQuery = require('jquery');
}
```

**Comment by RedNoo** [comment]
I'm getting same error, @rinkesh412 did you find any solution?

**Comment by mittalyashu** [comment]
@rinkesh412 Are you using this `@gridsome/plugin-google-analytics` package?

**Comment by mittalyashu** [comment]
I am facing the exact same issue.

**Comment by rinkesh412** [comment]
> I'm getting same error, @rinkesh412 did you find any solution?

No.

**Comment by dominiquedutra** [comment]
@rinkesh412 

It's hard to tell without knowing exactly what you are trying to accomplish with jQuery. Is it a full featured plugin? Is it a simple function / dom manipulation?

Keep in mind that (almost) everything will work on Dev mode because it is not rendering the html server side, it's just live serving so you could hook a jquery calendar plugin in there and have it working.

Please read the "Without SSR support" block for example of how to import jQuery.
https://gridsome.org/docs/assets-scripts/#without-ssr-support

Wrap any html blocks that are manipulated by jQuery with <Client-Only></Client-Only> tags in order to tell Gridsome that it should not touch this on build.

Also, I would strongly recommend you not to mix jQuery with VueJS (Gridsome). I know there are a lot jQuery material out there but you will thank me later. Basically you can accomplish everything with vue components.

**Comment by shayaulman** [comment]
I also faced the error `window is not defined` at build time.
I figured out that this is because Gridsome renders the code on the server where `window` is not defined. 
So my solution was to call `window` from a Vue life-cycle hook that is **not** called during server side rendering, like `mounted()`.
See the list of the life-cycle hooks in the [Vue docs](https://vuejs.org/v2/api/#Options-Lifecycle-Hooks), to see which is rendered only on client side.

**Comment by Berkmann18** [comment]
I'm facing the same issue but using [`vue-scrollmagic`](https://github.com/magr0s/vue-scrollmagic/).

**Comment by matteodem** [comment]
Using `process.isClient` and `global` instead of `window`  worked for me.

```js
if (process.isClient) {
  vuexLocalPlugin = new VuexPersistence({
    storage: global.localStorage,
  }).plugin
}
```

**Comment by ukristen** [comment]
> I'm facing the same issue but using [`vue-scrollmagic`](https://github.com/magr0s/vue-scrollmagic/).

@Berkmann18 did you solve your issue with vue-scrollmagic?

**Comment by Berkmann18** [comment]
@ukristen Using `vue-scrollmagic`? Yes.
Using `vue-beautiful-chat`? Nope.

**Comment by ukristen** [comment]
Can you share your solution for vue-scrollmagic? I have the same issue using ks-vue-scrollmagic.

**Comment by Berkmann18** [comment]
@ukristen Have you looked at my comment on the issue I raised on the `ks-vue-scrollmagic` repo? TL;DR: Using more bare-bones approach following one of the Gridsome No-SSR solutions (none of which work for something like `vue-beautiful-chat` so far :s).

**Comment by ukristen** [comment]
Sorry, didn't see that it was in the 'closed' issues section. Seeing it now.

**Comment by weleo** [comment]
> Using `process.isClient` and `global` instead of `window` worked for me.
> 
> ```js
> if (process.isClient) {
>   vuexLocalPlugin = new VuexPersistence({
>     storage: global.localStorage,
>   }).plugin
> }
> ```

Could you share a full example of your main.js? I am struggling with the implementation😂

**Comment by sureshvv** [comment]
gapi_client.js has a reference to "window". This is causing failure when I build.

**Comment by m3hari** [comment]
Here is how it works with `vuex-persistedstate`

**src/store/index.js**
```js
import createPersistedState from 'vuex-persistedstate'
import cart from './cart'

const store = {
  modules: {
    cart,
  },
  plugins: [],
}

if (process.isClient) {
  store.plugins.push(createPersistedState({}))
}

export default store
```

**main.js**

```js
import store from '~/store'

export default function (Vue, { appOptions, router, head, isClient }) {
  
  appOptions.store = new Vuex.Store(store)
}
```

**Comment by seeratawan01** [comment]
I was facing same issue, resolve it by adding following into my main.js file

```javascript
if (process.isClient) {
    const VueCountdownTimer = require('vuejs-countdown-timer').default;
    Vue.use(VueCountdownTimer);
}
```

**Comment by julyevg** [comment]
> ndo construyo.
en mi caso es con vue-images-loaded y no tengo idea ;(
