### ISSUE TITLE
Error: Duplicate key for property path: 

### ISSUE THREAD

**Issue by phillipweston** [gridsome/gridsome#805]
## Description

When attempting to dynamically create pages, I get:
```
Error: Duplicate key for property path: /ltc-terms
```

### Steps to reproduce

In my `gridsome.config.js`, I have:
```
// This is where project configuration and plugin options are located. 
// Learn more: https://gridsome.org/docs/config

// Changes here require a server restart.
// To restart press CTRL + C in terminal and run `gridsome develop`

module.exports = {
  siteName: '',
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'content/posts/*.md',
        typeName: 'BlogPage'
      }
    },
    {
      use: '@gridsome/source-filesystem',
      options: {
        baseDir: 'content/pages',
        path: '**/*.md',
        typeName: 'MainPage'
      }
    },
    {
      use: `gridsome-plugin-netlify-cms`,
      options: {
        publicPath: `/admin`
      }
    }
  ]
}
```

My `gridsome.server.js`:

```
// Server API makes it possible to hook into various parts of Gridsome
// on server-side and add custom data to the GraphQL data layer.
// Learn more: https://gridsome.org/docs/server-api

// Changes here require a server restart.
// To restart press CTRL + C in terminal and run `gridsome develop`


const nodeExternals = require('webpack-node-externals')


module.exports = function (api) {
  api.loadSource(({ addContentType }) => {
    // Use the Data Store API here: https://gridsome.org/docs/data-store-api
  })

  api.createPages(async ({ createPage, graphql }) => {
    // Use the Pages API here: https://gridsome.org/docs/pages-api
    const blog = await graphql(`{
      allBlogPage {
        edges {
          node {
            id
            date
            summary
            path
            tags
            excerpt
            title
            content
          }
        }
      }
    }`)

    blog.data.allBlogPage.edges.forEach(({ node }) => {
      createPage({
        path: `/${node.path}`,
        component: './src/templates/Blog.vue',
        context: {
          id: node.id,
          path: node.path,
          summary: node.summary,
          content: node.content,
          title: node.title,
          date: node.date
        }
      })
      console.log('createPage', node.path)
    })
  })

  api.createPages(async ({ createPage, graphql }) => {
    const main = await graphql(`{
        allMainPage {
          edges {
            node {
              id
              date
              path
              title
              content
            }
          }
        }
      }`)

    main.data.allMainPage.edges.forEach(({ node }) => {
      createPage({
        path: `${node.path}`,
        component: './src/templates/MainPage.vue',
        context: {
          id: node.id,
          path: node.path,
          body: node.content,
          title: node.title,
          date: node.date
        }
      })
      console.log('createPage', node.path, node.content)
    })
  })

  api.chainWebpack((config, { isServer }) => {
    config.mode('development')
    if (isServer) {
      config.externals([
        nodeExternals({
          whitelist: [/^Vuetify/]
        })
      ])
    }
  })
}
```

An example of `content/pages/ltc-terms.md`
```
---
title: LTC Terms
date: 2012-09-06
path: /ltc-terms
---

LTC Terms go here
```

### Expected result

I expect the main pages to be created just like the blog post pages. Their format identical to blog posts. Yet I get weird issues, blog posts don't need a pre-pended `/`, but it complains if I don't add it for the main pages. When I do, I get:

### Actual result

```
createPage /ltc-terms <p>LTC Terms go here</p> (this is just a console.log)

Error: Duplicate key for property path: /ltc-terms
    at UniqueIndex.set (/Users/atomic/ltc/gridsome-ltctree/node_modules/lokijs/src/lokijs.js:7329:17)

    at Collection.add (/Users/atomic/ltc/gridsome-ltctree/node_modules/lokijs/src/lokijs.js:5974:31)
    at Collection.insertOne (/Users/atomic/ltc/gridsome-ltctree/node_modules/lokijs/src/lokijs.js:5738:17)
    at Collection.insert (/Users/atomic/ltc/gridsome-ltctree/node_modules/lokijs/src/lokijs.js:5677:21)
    at Route.addPage (/Users/atomic/ltc/gridsome-ltctree/node_modules/gridsome/lib/pages/pages.js:447:19)
    at Pages.createPage (/Users/atomic/ltc/gridsome-ltctree/node_modules/gridsome/lib/pages/pages.js:175:18)
    at Object.createPage (/Users/atomic/ltc/gridsome-ltctree/node_modules/gridsome/lib/app/actions.js:258:24)
    at Template.createPage (/Users/atomic/ltc/gridsome-ltctree/node_modules/gridsome/lib/plugins/TemplatesPlugin.js:375:23)
    at createTemplate (/Users/atomic/ltc/gridsome-ltctree/node_modules/gridsome/lib/plugins/TemplatesPlugin.js:295:24)
    at TemplatesPlugin.api.createManagedPages (/Users/atomic/ltc/gridsome-ltctree/node_modules/gridsome/lib/plugins/TemplatesPlugin.js:332:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have only a single file in that directory, but it has the same issues with all files in that directory. I thought perhaps pages was a global restricted word, so renamed it to main with no luck.
### Environment

Paste the information here as shown by `gridsome info`

It says `gridsome info` is not a command, so here is my package.json:
```
{
  "name": "ltctree",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "@gridsome/cli": "^0.3.1",
    "@gridsome/source-filesystem": "^0.6.2",
    "@gridsome/transformer-remark": "^0.4.0",
    "@mdi/font": "^4.5.95",
    "apollo-fetch": "^0.7.0",
    "axios": "^0.19.0",
    "global": "^4.4.0",
    "graphql-tag": "^2.10.1",
    "gridsome": "^0.7.1",
    "gridsome-plugin-netlify-cms": "^1.0.9",
    "moment": "^2.24.0",
    "netlify-cms": "^2.9.7",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.2",
    "vue-the-mask": "^0.11.1",
    "vuetify": "^2.0.10"
  },
  "devDependencies": {
    "material-design-icons-iconfont": "^5.0.1",
    "webpack-node-externals": "^1.7.2"
  }
}
```

Thanks in advance for any help troubleshooting this!

**Comment by RomainLanz** [comment]
Hey @phillipweston! 👋 

I may be wrong, but I believe the file in `content/pages` are automatically created (since you used `@gridsome/source-filesystem`).

Therefore, since you are trying to add a page manually in your `gridsome.server.js` it complains about a duplicated path (because it has already been added).

**Comment by phillipweston** [comment]
huh @RomainLanz, thanks for the tip! my understanding was that `@gridsome/source-filesystem` would just pull the content of those pages into GraphQL. Is there something else I use if I want them ingested, but not auto created?

**Comment by phillipweston** [comment]
Thanks for your comment, it was useful in troubleshooting the problem.

If the `typeName` matches a valid `template/<typeName>.vue`, it will automatically create the pages. If you want `@gridsome/source-filesystem` to simply import items into GraphQL for your own use, then make sure the template name does not match the type.

**Comment by brycewray** [comment]
@phillipweston Gridsome newbie here. I have been reading both this issue page and "Next and previous node in collections" [Issue 177](https://github.com/gridsome/gridsome/issues/177), and I guess I'm missing what you're saying here and what @hjvedvik says [here](https://github.com/gridsome/gridsome/issues/177#issuecomment-487680495), because I can't make it work &mdash; I keep getting the `Duplicate key for property path` error. Here is what I have taken your last comment to mean (but obviously I'm wrong):

If `gridsome.config.js` includes the following:
```
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: './content/posts/**/*.md',
        typeName: 'Post'
      }
    },
  ],
  templates: {
    Post: [
      {
        path: '/posts/:year/:month/:fileInfo__name',
        component: './src/templates/Post.vue',
      }
    ],
  },
```

... then `gridsome.server.js` should **not** include the following:
```
      createPage({
        path: node.path,
        component: './src/templates/Post.vue',
        context: {
          id: node.id,
          prevId: prev ? prev.node.id : null,
          nextId: next ? next.node.id : null
        }
      })
```
I have tried assigning different templates in `gridsome.config.js` and different components in `gridsome.server.js` but keep getting that `Duplicate key for property path` error, so I'm pretty sure I've simply misunderstood what you and @hjvedvik were saying. I would be grateful if you could set me straight on an instruction that sounds simple but, at least for me, clearly isn't.

**Comment by spencerwooo** [comment]
@brycewray I was able to resolve this issue by simply assigning a different name for my `Post.vue` file (by renaming it to `BlogPost.vue` and changing all relevant imports).

To my understanding, because the `typeName` fed into `@gridsome/source-filesystem` is `Post`, and the template inside `/src/template` is also named `Post.vue`, `@gridsome/source-filesystem` will pick up all `Post` type pages and populate them automatically. And when you use `createPage()` afterwards, because `Post` type pages are already generated, `gridsome` will eventually complain about `Duplicate keys`.

![image](https://user-images.githubusercontent.com/32114380/81504405-961b6800-931b-11ea-95fc-4001d609ae27.png)

Also, as a reference, the [noxify/gridsome-starter-casper-v2](https://github.com/noxify/gridsome-starter-casper-v2) Gridsome theme did a very nice job for generating previous and next nodes.

**Comment by brycewray** [comment]
@spencerwooo Thanks very much for this helpful information.
