### ISSUE TITLE
Help me to remove data-vue-tag="ssr"

### ISSUE THREAD

**Issue by thuyteq** [gridsome/gridsome#813]
Dear Gridsome Team,

I have used Gridsome and feel very happy.
I have a small question. My client for SEO look at html we generated use Gridsome and see that:

```
<meta data-vue-tag="ssr" name="og:url" content="https://*********/" />
```

They want to change into ↓

```
<meta name="og:url" content="https://*********/" />
```
(They do not want `data-vue-tag="ssr" ` appear in meta tag).

I look at document but could not found any information related how to customize this request.
Please help me to improve this issue.

Many thanks !!!

**Comment by hjvedvik** [comment]
Hi, @thuyteq. The `data-*` attributes are necessary for `vue-meta` (which Gridsome uses to handle tags in the head section) to function correctly and cannot be removed, unfortunately. I don't think they should matter for SEO purposes, but if you have to remove them, then you must add the tags manually instead of using `metaInfo`.

**Comment by zacnomore** [comment]
Question answered by https://github.com/gridsome/gridsome/issues/813#issuecomment-555914305
