### ISSUE TITLE
TypeError: Cannot read property 'FullPath' of undefined.

### ISSUE THREAD

**Issue by darrylmorley** [gridsome/gridsome#875]
Hi,

I get this error when trying to build:

```
Could not generate HTML for "/guns/winchester-sxp-defende-r12-az-n45951/":
TypeError: Cannot read property 'FullPath' of undefined
```

This is due to a few records in my collection (that is pulled from an api) missing images. Is there any way to skip these records on build?

Thanks,

**Comment by dominiquedutra** [comment]
@darrylmorley 
Thats gridsome telling you something is wrong with your build. Your website may look weird if it just renders without the image.

If that image is not necessary and you have taken precautions so that the page renders fine (I mean CSS and Layout-wise) without it, you should wrap the image rendering on a v-if v-else vue tag - conditional rendering.

```
<div class="gun-list">
  <div class="gun" v-for="gun in guns">
    <h1>{{ gun.model }}</h1>
    <template v-if="gun.thumbnail.FullPath">
      <img :src="gun.thumbnail.FullPath">
    </template>
    <template v-else>
      //You have no FullPath! Maybe render some placeholder image?
    <template>
  </div>
</div>
```

Best regards,

**Comment by darrylmorley** [comment]
As simple as that, perfect, thanks.
