### ISSUE TITLE
Router handles normal anchor links as internal URLs

### ISSUE THREAD

**Issue by cswebservice** [gridsome/gridsome#939]
## Description
We're using a mix of Gridsome pages and Wordpress pages within the same domain.
/:slug will display a gridsome wordpress blog post and /impressum should show a normal page outside gridsome.

The event listener in the following file will handle normal <a> links as internal vue links and show a 404 page instead of making a normal page reload to the given address:
https://github.com/gridsome/gridsome/blob/a4e22d6e8f21be360a7e750dcfea27180910cbe4/gridsome/app/entry.client.js#L39-L78

As you already mentioned as a comment you wanna remove this code. Can you simply add a config option to disable that behavior in general? default value could still be to enable the feature.

### Steps to reproduce
Add a `<g-link to="http://my.domain/foo">` and a `<a href="http://my.domain/bar">`. Both will stay within gridsome.

### Expected result
As in Vue a normal <a> should always redirect like the default behavior of anchors.

### Actual result
Gridsome is listing on clicks and routing pages within the same domain.

### Environment
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 72.0.1
    Safari: 13.0.4
  npmPackages:
    @gridsome/cli: ^0.3 => 0.3.1 
    @gridsome/source-wordpress: ^0.5 => 0.5.2 
    gridsome: ^0.7 => 0.7.12 
    gridsome-plugin-gtm: ^0.1.1 => 0.1.1

**Comment by ralph** [comment]
I agree with @cswebservice that this event handler breaks external links pointing to the same domain, so this functionality should either be opt-in or go away.

Ideally, Gridsome should expose a new config option `enableAnchorLinks`, which should be `false` by default. So people relying on this functionality can easily opt-in, and others don't get crazy wondering why external links are not working because an event handler has been registered on `document`. Without a config option, it's very hard to get rid of this behaviour, as you don't have a reference to the original event handler. And it breaks stuff in cases when you have a load balancer routing e.g. your marketing pages to gridsome and other pages to a CMS, for example.

**Comment by a-kriya** [comment]
@cswebservice This ticket can probably be closed now since your PR was merged and released.

Should the config be added to the documentation, though? I'm not sure what needs to happen before
```
// TODO: remove this behavior
// let Vue router handle internal URLs for anchors in innerHTML
```
can be addressed. @hjvedvik?
