### ISSUE TITLE
Does this project have a future?

### ISSUE THREAD

**Issue by jackmahoney** [gridsome/gridsome#946]
I encountered a bug in Gridsome and see there are many open issues and pull requests that have received no comment or feedback for some time. Is this project still being actively maintained? If not I feel like I have made a bad investment of my time in building a site with Gridsome. If so then do you have a plan to address the open issues? I've resorted to forking the project and patching it myself at this stage.

**Comment by dominiquedutra** [comment]
Just a note @jackmahoney many of the open issues are really questions and requests. We have all kinds:

- Questions that do not make sense (I mean I read it and cannot understand what the user meant);
- People that come here, ask a question, someone replies and and the OP never comes back here to follow up on the issue;
- People requesting features that they could implement themselves / rather specific features.

I would suggest doing a thoroughly cleanup of issues that won't go anywhere. That would surely cut the issues number in half.

All in all I would say the core of Gridsome is working and I have it deployed in production. That said, I agree that it could use some PR maintenance etc. 

About issue cleanup, I could do some of that if the founders of the project agree.

**Comment by hjvedvik** [comment]
@jackmahoney The project is still maintained and we have lots of plans for it in the future. We are currently working on other features that are not part of this repository, so that's why it has been a bit quiet here lately. Feel free to open a PR if you are able to fix that bug :)

And, yes, @dominiquedutra. Would really appreciate it if you want to look through the issues and do a cleanup! :) I think most of them are questions that have been answered. But just tag me if there are some bugs reports that we have missed.

Maybe a bot to auto close issues after a while would be an idea too.

**Comment by jackmahoney** [comment]
Yes please understand that I very much appreciate the work that has gone into this project. I just worry a bit about the stability at this stage. Let's see how it works out in the end.
