### ISSUE TITLE
Plugin request: Shiki remark plugin

### ISSUE THREAD

**Issue by tomtev** [gridsome/gridsome#97]
## Summary
Shiki is a beautiful Syntax Highlighter. 
http://shiki.matsu.io/

### Motivation
We already have a remark plugin for prismjs (https://gridsome.org/plugins/plugin-remark-prismjs), but Shiki looks nice and plays nice with .Vue code syntax.

VuePress already has a plugin for it: https://github.com/octref/shiki/blob/master/packages/vuepress-plugin/README.md

**Comment by EldoranDev** [comment]
This Plugin got moved to its own repository and is published on npm.

[GitHub](https://github.com/EldoranDev/gridsome-plugin-remark-shiki/)
[NPM](https://www.npmjs.com/package/gridsome-plugin-remark-shiki)

**Comment by rsclarke** [comment]
FWIW I was interested in mutating the HAST tree instead of inserting a HTML node in MDAST and subsequently wrote [rehype-shiki](https://github.com/rsclarke/rehype-shiki) based of @EldoranDev's plugin and [rehype-highlight](https://github.com/rehypejs/rehype-highlight).

Out of the box transformer-remark uses `remark-html` but we can change this with the `stringifier` option to allow mutation on the HAST tree.

In `gridsome.config.js`:
```javascript
const stringify = require('rehype-stringify')

module.exports = {
  transformers: {
    remark:  {
      stringifier = stringify,
      plugins: [
        //remark plugins here
        [ 'remark-rehype' ]
        //rehype plugins here
        [ 'rehype-shiki' ]
      ]
    }
  }
}
