### ISSUE TITLE
Is SSR supported?

### ISSUE THREAD

**Issue by simplenotezy** [gridsome/gridsome#971]
I am looking to create a WordPress theme, and I'd like to ensure that Server Side Rendering is supported, but I am not quite sure if this is something gridsome supports? I tried looking through the documentation, but really can't find anything but a recommendation to Nuxt as alternative for focus on SSR.

**Comment by zacnomore** [comment]
I hope this isn't too indirect of an answer, I'm trying to read into your use-case a bit here.

Gridsome is a SSG so it generates static HTML files at build time. SSR creates those HTML files at runtime.

If your content is static, static site generators and server side rendering do the same job. All it would take to get your SSG to act like SSR is run the build when your content is updated. You get a bunch of performance from that headless, CDN hosted site, the SEO benefits of SSR and the only thing that your missing is the dynamic content. You can still have highly dynamic content but you need to fetch it from within the client.

You can host your entire site on a CDN because it's all static files. That's not something you can do with SSR. You can cache your pages but you still need to setup a server behind that cache. There's some cool platforms that make this really easy to do like [Zeit](https://zeit.co/) and [Netlify](https://www.netlify.com/).

**Comment by zacnomore** [comment]
Just a note of clarification, SSG is SSR running as a build step. They're not really distinct but SSR is often discussed in terms of a SSR as part of a production runtime so I was hoping to draw that distinction here.

**Comment by zacnomore** [comment]
Closing as answered, we can certainly reopen if you'd like more info!

**Comment by simplenotezy** [comment]
Hey @zacnomore thanks a bunch for your in-depth answer. I defientently made more sense to me as I've been developing some more in Vue and Nuxt.
Static site sounds incredible, and at first I didn't think it was possible with a WooCommerce shop, but it sounds so, as you say, some of the static content can still be dynamic on the client, by fetching some content at runtime. Eg a search page, create order page,etc.
Still learning but really excited about all this - usually my focus was backend, but this new frontend world is exciting.
Anyhow, I'm still not sure how gridsome could help me, compared to how I use Nuxt.js today

**Comment by zacnomore** [comment]
I'm not an expert by any means but I can offer a little. Nuxt is large and general purpose while Gridsome is focused on providing speed out of the box. There's plenty of advanced features that aren't in Gridsome right now but it still has it's place. A smaller project can easily get lost in the boilerplate and configuration of Nuxt. A large project would be hamstrung by Gridsome, it lacks required features like i18n right now which is a non-starter for many. While feature parity will never happen, Nuxt will never be as lightweight and easy to learn as Gridsome either.
