### ISSUE TITLE
Question: Download and process remote images with remark in md files

### ISSUE THREAD

**Issue by BenRoe** [gridsome/gridsome#987]
Hello,
i have md files with some images tags like `<img src="https://images.unsplash.com/photo-1559291001-693fb9166cba"`.

Can someone give me a hint how to download remote images and process them.
First idea is the the `transformer-remark`, but i have no idea how to start.

Can someone help and give some hints. Many thanks.

**Comment by noxify** [comment]
Hi,

we had a similar discussion last week in the discord chat.

After a lot of try&error i was able to download an image based on a source field. 

I know that your question is a bit different, but maybe it could work as a workaround.


https://github.com/noxify/gridome-plugin-image-download

Btw. You could also create your own transformer plugin, checking if there is an image and is the url is a remote one, if so - download it and change the path to the local image ( feel free to copy what you need from my plugin )

Related topics:
#60 #894 #459 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by noxify** [comment]
Hi @BenRoe ,

I had some time to create a remark plugin which checks for images with a remote url.

Maybe this helps you to solve your problem.


https://github.com/noxify/gridsome-plugin-remark-image-download

**Comment by BenRoe** [comment]
@noxify Great 👍 
Does this work with <img> tag in markdown files?
I use the img tag instead the regular markdown, because i have to set the width. If i am right this is not possible on github with the markdown img tag.

**Comment by noxify** [comment]
Hi @BenRoe,

I have tested it, but unfortunately it's not possible.

The reason is the following:

If you're using 

```
<img src="https://raw.githubusercontent.com/gridsome/gridsome-starter-blog/master/content/posts/images/alexandr-podvalny-220262-unsplash.jpg" alt="Remote Image" width="100"/>
```

the node for this, is something like this:

```
{
    "type": "html",
    "value": "<img src=\"https://raw.githubusercontent.com/gridsome/gridsome-starter-blog/master/content/posts/images/alexandr-podvalny-220262-unsplash.jpg\" alt=\"Remote Image\" width=\"100\"/>",
    "position": {
        "start": {
            "line": 4,
            "column": 1,
            "offset": 9
        },
        "end": {
            "line": 4,
            "column": 175,
            "offset": 183
        },
        "indent": []
    }
}
```
But the transformer transforms only nodes from type `image`.

But you could use my transformer as startpoint and changing the logic to fetch nodes from type `html`. Then you only have to filter the result nodes to get only nodes where the value contains `<img` and the `src` is an external url.

My transformer is based on: 
https://github.com/gridsome/gridsome/blob/master/packages/transformer-remark/lib/plugins/image.js
( Check line 28/29 )

This means, if you find a may to define the `width`  to

```
![Image](https://unsplash.com/images/alexandr-podvalny-220262-unsplash.jpg)
```

The generated html will contain the defined `width` value.

Unfortunately, I haven't found a way to do this, yet.

@tomtev / @hjvedvik - Do you know how to define this?

**Comment by hacknug** [comment]
Would using this solve your issues? https://github.com/arobase-che/remark-attr

**Comment by noxify** [comment]
I close this issue for now, feel free to reopen :)
